/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import auxiliar.Avisos;
import auxiliar.MostrarDados;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author monier
 */
public class Aguardando extends javax.swing.JDialog {

    public static Aguardando s_telaAguardando;

    private int c_contador;
    
    /**
     * Creates new form Aguardando1
     */
    public Aguardando(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
    
        
        threadTempoTarefa.setDelay(1000); 
        lb_dialogo.setText(""); 
        c_contador = 0;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        threadTempoTarefa = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_dialogo = new javax.swing.JLabel();

        threadTempoTarefa.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                threadTempoTarefaOnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(new ImageIcon(Login.class.getResource("/imagens/icones/16/icone-notificacao.png"), Avisos.FACECARD_FULL).getImage());
        setResizable(false);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/carregando.gif"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        lb_dialogo.setBackground(new java.awt.Color(0, 0, 0));
        lb_dialogo.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        lb_dialogo.setForeground(new java.awt.Color(255, 255, 255));
        lb_dialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_dialogo.setText("Aguarde enquanto está processando...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_dialogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_dialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void threadTempoTarefaOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threadTempoTarefaOnTime
        c_contador++;

        System.err.println(c_contador);

        if (c_contador <= 15) {

            lb_dialogo.setText(Avisos.TEXTO_AGUARDE_PROCESSO);
            lb_dialogo.setForeground(Color.WHITE);

        }

        if (c_contador > 15 && c_contador <= 30) {

            lb_dialogo.setText(Avisos.TEXTO_AGUARDE_PROCESSO);
            lb_dialogo.setForeground(Color.GREEN);

        }

        if (c_contador > 30 && c_contador <= 60) {

            lb_dialogo.setText(Avisos.TEXTO_PASSOU_30_SEG);
            lb_dialogo.setForeground(Color.CYAN);

        }

        if (c_contador > 60 && c_contador <= 90) {

            //mostra aviso de ddemora mais q o normal...
            lb_dialogo.setText(Avisos.TEXTO_DEMORANDO_ANORMAL);
            lb_dialogo.setForeground(Color.YELLOW);
        }

        if (c_contador > 90) {
            lb_dialogo.setText(Avisos.TEXTO_TEMPO_ESGOTADO);
            lb_dialogo.setForeground(Color.RED);
        }


    }//GEN-LAST:event_threadTempoTarefaOnTime

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        lb_dialogo.setText(Avisos.TEXTO_AGUARDE_PROCESSO);
        lb_dialogo.setForeground(Color.WHITE); 
        c_contador = 0;
        threadTempoTarefa.start();
//        System.err.println("MOstrou. inicia thread");  
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        lb_dialogo.setText(Avisos.TEXTO_AGUARDE_PROCESSO);
        lb_dialogo.setForeground(Color.WHITE);
        c_contador = 0;
        threadTempoTarefa.stop();
//        System.err.println("Escondeu. parou"); 
    }//GEN-LAST:event_formComponentHidden

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if(evt.getClickCount() == 4){

            if(c_contador >= 30){
                lb_dialogo.setText(Avisos.TEXTO_AGUARDE_PROCESSO);
                lb_dialogo.setForeground(Color.WHITE); 
                s_telaAguardando.setVisible(false); 
                c_contador = 0;
                threadTempoTarefa.stop();
            }else{
                MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.TEXTO_AVISO_FINALIZAR_AGUAR, "aviso");
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_dialogo;
    private org.netbeans.examples.lib.timerbean.Timer threadTempoTarefa;
    // End of variables declaration//GEN-END:variables
}
