/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BaixaArquivo.java
 *
 * Created on 11/11/2011, 16:18:24
 */

package formularios;

import auxiliar.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Ayrton Monier
 */
public class BaixaArquivo extends javax.swing.JFrame {

    private String c_nomeArquivo = "";
    
    public int c_contador;

    /** Creates new form BaixaArquivo */
    public BaixaArquivo(String l_nomeArquivo, int l_tamanho) {

        initComponents();

        //teste tamanho de arquivo
        c_nomeArquivo = l_nomeArquivo;
        String l_tamanhoMostrar = null;
        double l_tamanhoEmMB = SolicitarDados.s_SolicitarDados.pegaTamanhoArquivoEmMB(l_tamanho);

            //CASO SEJA MENOS QUE 0 MB mostra tamanho em bytes
            if(l_tamanhoEmMB <= 0)
                l_tamanhoMostrar = l_tamanho+" bytes";
            else
                l_tamanhoMostrar = l_tamanhoEmMB+" MB";
        
        l_nomeArquivo = SolicitarDados.s_SolicitarDados.trataNomeArquivoPara50caracteres(l_nomeArquivo);
        lb_nomeArquivo.setText(l_nomeArquivo);
        lb_tamanhoArq.setText(l_tamanhoMostrar);
        
        this.setTitle(Avisos.TIT_JAN_BAIXA_ARQUIVO); 
        
        threadTempoTarefa.setDelay(1000); 
        threadTempoTarefa.start();
        c_contador = 0;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        threadTempoTarefa = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        lb_iconeRecebendoArq = new javax.swing.JLabel();
        lb_acompanhaRecebimento = new javax.swing.JLabel();
        lb_apelidoReceptor = new javax.swing.JLabel();
        lb_apelidoEmissor = new javax.swing.JLabel();
        pb_recebendoArquivo = new javax.swing.JProgressBar();
        bt_abrirArquivo = new javax.swing.JButton();
        bt_verDepois = new javax.swing.JButton();
        lb_logoBaixando = new javax.swing.JLabel();
        lb_nomeArquivo = new javax.swing.JLabel();
        lb_tamanhoArq = new javax.swing.JLabel();

        threadTempoTarefa.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                threadTempoTarefaOnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(new ImageIcon(BaixaArquivo.class.getResource(Icones.ARQUIVOS), "Facecard MS").getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb_iconeRecebendoArq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/conectando-pessoa.gif"))); // NOI18N

        lb_acompanhaRecebimento.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_acompanhaRecebimento.setText("Recebendo arquivo...");

        lb_apelidoReceptor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_apelidoReceptor.setForeground(new java.awt.Color(255, 0, 0));
        lb_apelidoReceptor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_apelidoReceptor.setText("Apelido 2");

        lb_apelidoEmissor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_apelidoEmissor.setForeground(new java.awt.Color(255, 0, 0));
        lb_apelidoEmissor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_apelidoEmissor.setText("Apelido 1");

        pb_recebendoArquivo.setBackground(new java.awt.Color(255, 255, 255));
        pb_recebendoArquivo.setForeground(new java.awt.Color(0, 0, 204));

        bt_abrirArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/arquivo-abrir.png"))); // NOI18N
        bt_abrirArquivo.setText("Visualizar o arquivo baixado");
        bt_abrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_abrirArquivoActionPerformed(evt);
            }
        });

        bt_verDepois.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/cancelar.png"))); // NOI18N
        bt_verDepois.setText("Cancelar");
        bt_verDepois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verDepoisActionPerformed(evt);
            }
        });

        lb_logoBaixando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/logo-baixando-arquivo.png"))); // NOI18N

        lb_nomeArquivo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_nomeArquivo.setForeground(new java.awt.Color(0, 0, 204));
        lb_nomeArquivo.setText("Nome do arquivo");

        lb_tamanhoArq.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_tamanhoArq.setForeground(new java.awt.Color(0, 0, 204));
        lb_tamanhoArq.setText("tamanho");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_iconeRecebendoArq)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_apelidoEmissor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_apelidoReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_acompanhaRecebimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_logoBaixando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pb_recebendoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_abrirArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_verDepois))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_nomeArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_tamanhoArq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lb_logoBaixando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_iconeRecebendoArq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_apelidoEmissor)
                    .addComponent(lb_apelidoReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nomeArquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_tamanhoArq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_acompanhaRecebimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pb_recebendoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_verDepois, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_abrirArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_verDepoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verDepoisActionPerformed
        if(bt_verDepois.getText().equals("Cancelar")){

        boolean l_cancelar = MostrarDados.s_MostrarDados.mostraAvisoConfirmacao(Avisos.TITULO_CANCELA_BAIXAR_ARQ, Avisos.CANCELA_BAIXAR_ARQ, Icones.ARQUIVO_BAIXAR);

            if(l_cancelar){

                dispose();
                c_contador = 0;
                threadTempoTarefa.stop();

            }else
                return;
        }else{
            dispose();
            Moniersn.s_telaMsn.setVisible(true); 
        }

    }//GEN-LAST:event_bt_verDepoisActionPerformed

    private void bt_abrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_abrirArquivoActionPerformed
        MostrarDados.s_MostrarDados.abrirArquivoSelecionado(c_nomeArquivo, Diretorios.PASTA_BAIXADOS);
    }//GEN-LAST:event_bt_abrirArquivoActionPerformed

    private void threadTempoTarefaOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threadTempoTarefaOnTime
        c_contador++;

        System.err.println("segundos: " + c_contador);

        if (c_contador == 7) {

            Moniersn.s_telaMsn.setVisible(true); 
            c_contador = 0;
            dispose();
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.TEXTO_TEMPO_LIMITE_OP_EXCEDIDO, "erro");
            threadTempoTarefa.stop();
        }
    }//GEN-LAST:event_threadTempoTarefaOnTime


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_abrirArquivo;
    public javax.swing.JButton bt_verDepois;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lb_acompanhaRecebimento;
    public javax.swing.JLabel lb_apelidoEmissor;
    public javax.swing.JLabel lb_apelidoReceptor;
    public javax.swing.JLabel lb_iconeRecebendoArq;
    public javax.swing.JLabel lb_logoBaixando;
    public javax.swing.JLabel lb_nomeArquivo;
    public javax.swing.JLabel lb_tamanhoArq;
    public javax.swing.JProgressBar pb_recebendoArquivo;
    public org.netbeans.examples.lib.timerbean.Timer threadTempoTarefa;
    // End of variables declaration//GEN-END:variables

}
