/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroUsuario.java
 *
 * Created on 21/12/2010, 07:51:03
 */

package formularios;


import auxiliar.*;
import java.awt.Color;
import javax.swing.*;
import java.util.Date;

/**
 *
 * @author f113cpd02
 */
public class CadastroUsuario extends javax.swing.JDialog {

    public static CadastroUsuario s_telaCadastroMoniersn;

    public boolean l_iniciado = false;
    
    //variáveis de classe do tipo BOOLEAN
    public boolean c_podeGravar = true; // indica que pode efetuar a gravação do registro

    //guarda a msg a exibir
    public String c_msg;

    //guarda a data de nascimento o formato ano-mes-dia
    public String c_dataNascimento;

    //quarda o sexo selecionado
    public String c_sexo;



    /** Creates new form CadastroUsuario */
    public CadastroUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //deixa o form com um tamanho que não apareça logo os campos de senha
        this.setSize(468, 452);
        this.setTitle(Avisos.TIT_JAN_CADASTRO_USUARIO); 

        Data.atualizaDataHora();
        lb_dataCadatro.setText(Data.s_dataAtualPorExtenso);
        
        Login.l_cadIniciado = true;
        
        CadastroUsuario.jp_infoSeguranca.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        gb_sexo = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jp_infoSeguranca = new javax.swing.JPanel();
        pf_senha = new javax.swing.JPasswordField();
        pf_conf_senha = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tf_resposta_secreta = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cb_pergunta_secreta = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        bt_confirmaCadastro = new javax.swing.JButton();
        cb_concorda = new javax.swing.JCheckBox();
        lb_politicaPriv = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_termosUso = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_sobrenome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_IconeHumorApelido = new javax.swing.JLabel();
        lb_nomeIconeHumor = new javax.swing.JLabel();
        lb_iconeSexo = new javax.swing.JLabel();
        lb_dataNascimento = new javax.swing.JLabel();
        lb_dataNiver = new javax.swing.JLabel();
        lb_sexo = new javax.swing.JLabel();
        lb_dataCadatro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tf_moniersn = new javax.swing.JTextField();
        bt_confirmar = new javax.swing.JButton();
        lb_contaApelido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_ano = new javax.swing.JComboBox();
        cb_dia = new javax.swing.JComboBox();
        cb_mes = new javax.swing.JComboBox();
        cb_humor = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        lb_contaNome = new javax.swing.JLabel();
        lb_contaSobrenome = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        rb_masculino = new javax.swing.JRadioButton();
        rb_feminino = new javax.swing.JRadioButton();
        lb_iconeMasculino = new javax.swing.JLabel();
        lb_iconeFeminino = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(new ImageIcon(Moniersn.class.getResource("/imagens/icones/16/icone-notificacao.png"), "MonierSN").getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jp_infoSeguranca.setBackground(new java.awt.Color(255, 255, 255));
        jp_infoSeguranca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações de segurança", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N

        pf_senha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pf_senha.setForeground(new java.awt.Color(204, 0, 0));

        pf_conf_senha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pf_conf_senha.setForeground(new java.awt.Color(204, 0, 0));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Confirmar senha:");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Senha:");

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 51, 255));
        jLabel27.setText("Resposta secreta:");

        tf_resposta_secreta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tf_resposta_secreta.setForeground(new java.awt.Color(204, 0, 0));
        tf_resposta_secreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_resposta_secretaActionPerformed(evt);
            }
        });
        tf_resposta_secreta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_resposta_secretaKeyReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/informacao.png"))); // NOI18N
        jLabel26.setText("Caso esqueça sua senha, responda a pergunta secreta.");

        cb_pergunta_secreta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_pergunta_secreta.setForeground(new java.awt.Color(204, 0, 0));
        cb_pergunta_secreta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Sua comida favorita", "Animal favorito", "Amigo de infância", "Número da sorte", "Personagem de quadrinho", "Nome da tataravó", "cor favorita", "ator / atriz favorito", "hobby", "Música favorita", "Filme favorito" }));
        cb_pergunta_secreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pergunta_secretaActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 255));
        jLabel25.setText("Pergunta secreta:");

        bt_confirmaCadastro.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bt_confirmaCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        bt_confirmaCadastro.setText("Ok");
        bt_confirmaCadastro.setToolTipText("Alterar minha senha de segurança!");
        bt_confirmaCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bt_confirmaCadastro.setEnabled(false);
        bt_confirmaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_confirmaCadastroActionPerformed(evt);
            }
        });

        cb_concorda.setBackground(new java.awt.Color(255, 255, 255));
        cb_concorda.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        cb_concorda.setForeground(new java.awt.Color(255, 0, 0));
        cb_concorda.setText("Concordo com a");
        cb_concorda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_concordaActionPerformed(evt);
            }
        });

        lb_politicaPriv.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        lb_politicaPriv.setForeground(new java.awt.Color(0, 0, 204));
        lb_politicaPriv.setText("Política de Privacidade");
        lb_politicaPriv.setToolTipText("Leia a Política de Privacidade...");
        lb_politicaPriv.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_politicaPriv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_politicaPrivMouseReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("e");

        lb_termosUso.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        lb_termosUso.setForeground(new java.awt.Color(0, 0, 204));
        lb_termosUso.setText("Termos de Uso");
        lb_termosUso.setToolTipText("Leia os Termos de Uso...");
        lb_termosUso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_termosUso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_termosUsoMouseReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("do Facecard™");

        javax.swing.GroupLayout jp_infoSegurancaLayout = new javax.swing.GroupLayout(jp_infoSeguranca);
        jp_infoSeguranca.setLayout(jp_infoSegurancaLayout);
        jp_infoSegurancaLayout.setHorizontalGroup(
            jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_infoSegurancaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jp_infoSegurancaLayout.createSequentialGroup()
                        .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jp_infoSegurancaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jp_infoSegurancaLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59)))
                        .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pf_conf_senha)
                            .addComponent(pf_senha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_confirmaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_infoSegurancaLayout.createSequentialGroup()
                        .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27))
                        .addGap(1, 1, 1)
                        .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_pergunta_secreta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_resposta_secreta)))
                    .addGroup(jp_infoSegurancaLayout.createSequentialGroup()
                        .addComponent(cb_concorda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_politicaPriv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_termosUso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jp_infoSegurancaLayout.setVerticalGroup(
            jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_infoSegurancaLayout.createSequentialGroup()
                .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_infoSegurancaLayout.createSequentialGroup()
                        .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pf_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pf_conf_senha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(bt_confirmaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_pergunta_secreta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_resposta_secreta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_infoSegurancaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_concorda, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_politicaPriv)
                    .addComponent(jLabel12)
                    .addComponent(lb_termosUso)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações Básicas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Data de Nascimento:");

        tf_nome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tf_nome.setForeground(new java.awt.Color(255, 0, 0));
        tf_nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_nomeFocusLost(evt);
            }
        });
        tf_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_nomeKeyReleased(evt);
            }
        });

        tf_sobrenome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tf_sobrenome.setForeground(new java.awt.Color(255, 0, 0));
        tf_sobrenome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_sobrenomeFocusLost(evt);
            }
        });
        tf_sobrenome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_sobrenomeKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("(1) Sobrenome:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_IconeHumorApelido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_IconeHumorApelido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/humor/novato.png"))); // NOI18N

        lb_nomeIconeHumor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_nomeIconeHumor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/amigo-r.png"))); // NOI18N

        lb_iconeSexo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_iconeSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/masculino.png"))); // NOI18N

        lb_dataNascimento.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_dataNascimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/nascimento.png"))); // NOI18N

        lb_dataNiver.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_dataNiver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/aniversario.png"))); // NOI18N

        lb_sexo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_sexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/feminino.png"))); // NOI18N

        lb_dataCadatro.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lb_dataCadatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/data-cadastro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_dataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_iconeSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_sexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lb_dataNiver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_nomeIconeHumor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_dataCadatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_IconeHumorApelido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_dataCadatro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nomeIconeHumor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_iconeSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_dataNiver, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_IconeHumorApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Nome:");

        jPanel4.setBackground(new java.awt.Color(237, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/smyles/neutro.png"))); // NOI18N
        jLabel6.setText("Apelido:");

        tf_moniersn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tf_moniersn.setForeground(new java.awt.Color(255, 0, 0));
        tf_moniersn.setToolTipText("Este é o seu usuário de acesso ao Open MonierSN");
        tf_moniersn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_moniersnActionPerformed(evt);
            }
        });
        tf_moniersn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_moniersnFocusLost(evt);
            }
        });
        tf_moniersn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_moniersnKeyReleased(evt);
            }
        });

        bt_confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        bt_confirmar.setText("Ok");
        bt_confirmar.setToolTipText("Verificar se já existe algum igual");
        bt_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_confirmarActionPerformed(evt);
            }
        });

        lb_contaApelido.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lb_contaApelido.setForeground(new java.awt.Color(255, 255, 255));
        lb_contaApelido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_contaApelido.setText("(0)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(tf_moniersn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lb_contaApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_confirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_contaApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_moniersn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/logo-criar-facecard.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/informacao.png"))); // NOI18N
        jLabel10.setText("O apelido é como você será conhecido na rede.");

        cb_ano.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_ano.setForeground(new java.awt.Color(204, 0, 0));
        cb_ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008" }));
        cb_ano.setEnabled(false);
        cb_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_anoActionPerformed(evt);
            }
        });

        cb_dia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_dia.setForeground(new java.awt.Color(204, 0, 0));
        cb_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cb_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_diaActionPerformed(evt);
            }
        });

        cb_mes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cb_mes.setForeground(new java.awt.Color(204, 0, 0));
        cb_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cb_mes.setEnabled(false);
        cb_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_mesActionPerformed(evt);
            }
        });

        cb_humor.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        cb_humor.setForeground(new java.awt.Color(204, 0, 0));
        cb_humor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "novato", "anjinho", "chorando", "sapeca", "estudando", "contente", "maquiada", "macaquinho", "aziado", "satisfeito", "onda", "hammm", "psiu", "ahaam", "ihhh", "kikiki", "lingua", "ooooh", "piscadela", "querendo rir", "segurando riso", "tristinho", "de boa", "olhudo", "deslumbrado", "mal", "injuriado", "saliente", "sideimal", "me entrego", "hun!", "rahh!", "indignado", "tenso", "amarrado", "bobo", "doido", "sede de beijo", "beijando", "piscador", "gargalhada", "surpreso", "he", "mongo", "vidrado", "brushh", "foi mal", "morgado", "pateta", "silasquei", "desesperado", "ih agora", "ihh caraca", "tedioso", "tristonho", "uh!", "aaaaaa", "amando", "assustado", "nhee", "tranquilo", "chorinho" }));
        cb_humor.setToolTipText("Altere a sua imagem de humor clicando nesta lista");
        cb_humor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_humorActionPerformed(evt);
            }
        });
        cb_humor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cb_humorKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Ícone de humor:");

        lb_contaNome.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lb_contaNome.setForeground(new java.awt.Color(0, 51, 255));
        lb_contaNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_contaNome.setText("(0)");

        lb_contaSobrenome.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lb_contaSobrenome.setForeground(new java.awt.Color(0, 51, 255));
        lb_contaSobrenome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_contaSobrenome.setText("(0)");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 11), new java.awt.Color(0, 51, 255))); // NOI18N
        jPanel5.setEnabled(false);

        rb_masculino.setBackground(new java.awt.Color(255, 255, 255));
        gb_sexo.add(rb_masculino);
        rb_masculino.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        rb_masculino.setForeground(new java.awt.Color(204, 0, 0));
        rb_masculino.setText("Masculino");
        rb_masculino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rb_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_masculinoActionPerformed(evt);
            }
        });

        rb_feminino.setBackground(new java.awt.Color(255, 255, 255));
        gb_sexo.add(rb_feminino);
        rb_feminino.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        rb_feminino.setForeground(new java.awt.Color(204, 0, 0));
        rb_feminino.setText("Feminino");
        rb_feminino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rb_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femininoActionPerformed(evt);
            }
        });

        lb_iconeMasculino.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lb_iconeMasculino.setForeground(new java.awt.Color(0, 204, 0));
        lb_iconeMasculino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/masculino.png"))); // NOI18N
        lb_iconeMasculino.setText("Nome (Ex: Fulano):");

        lb_iconeFeminino.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lb_iconeFeminino.setForeground(new java.awt.Color(0, 204, 0));
        lb_iconeFeminino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/feminino.png"))); // NOI18N
        lb_iconeFeminino.setText("Nome (Ex: Fulano):");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lb_iconeMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_masculino, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lb_iconeFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_feminino)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_masculino, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_iconeMasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_feminino, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_iconeFeminino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cb_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(133, 133, 133))
                            .addComponent(cb_humor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(tf_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lb_contaSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lb_contaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_contaNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_contaSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_dia)
                            .addComponent(cb_mes)
                            .addComponent(cb_ano)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_humor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_infoSeguranca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_infoSeguranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_humorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_humorActionPerformed
        MostrarDados.s_MostrarDados.iconeHumor(cb_humor.getSelectedItem().toString(), lb_IconeHumorApelido);
}//GEN-LAST:event_cb_humorActionPerformed

    private void tf_moniersnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_moniersnActionPerformed
        SolicitarDados.s_SolicitarDados.confirmarEditarInfoBasicas();
}//GEN-LAST:event_tf_moniersnActionPerformed

    private void bt_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_confirmarActionPerformed
        SolicitarDados.s_SolicitarDados.confirmarEditarInfoBasicas();
}//GEN-LAST:event_bt_confirmarActionPerformed

    private void cb_pergunta_secretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pergunta_secretaActionPerformed

}//GEN-LAST:event_cb_pergunta_secretaActionPerformed

    private void rb_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_masculinoActionPerformed
        c_sexo = "M";
        lb_iconeFeminino.setEnabled(false);
        lb_iconeMasculino.setEnabled(true);
        lb_iconeSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icones.SEX_MASC_16))); // NOI18N
        lb_sexo.setIcon(null);
        lb_sexo.setText("Masculino");

        
    }//GEN-LAST:event_rb_masculinoActionPerformed

    private void rb_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femininoActionPerformed
        c_sexo = "F";
        lb_iconeFeminino.setEnabled(true);
        lb_iconeMasculino.setEnabled(false);
        lb_iconeSexo.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icones.SEX_FEM_16))); // NOI18N
        lb_sexo.setIcon(null);
        lb_sexo.setText("Feminino");     
    }//GEN-LAST:event_rb_femininoActionPerformed

    private void cb_humorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cb_humorKeyTyped
       if(evt.getKeyChar() == ' ');
          tf_moniersn.requestFocus();
    }//GEN-LAST:event_cb_humorKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         s_telaCadastroMoniersn.setVisible(false); 
         Login.s_telaLogin.setVisible(true);
         
    }//GEN-LAST:event_formWindowClosing

    private void tf_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nomeKeyReleased
        if(!SolicitarDados.s_SolicitarDados.verificaCaracteresInvalidosCadastro(tf_nome.getText())){
            tf_nome.setText(tf_nome.getText().substring(0, (tf_nome.getText().length() -1)));
            String l_msg = Avisos.MSG_USE_PRIM_NOME_SEM_ESP;
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(l_msg, "aviso");
            tf_nome.requestFocus();
        }else{

            lb_nomeIconeHumor.setText(tf_nome.getText().toUpperCase()+" "+tf_sobrenome.getText().toUpperCase());
            tf_nome.setText(tf_nome.getText().toUpperCase());

                if(tf_nome.getText().length() > 12){
                    lb_contaNome.setText("(12)");
                    tf_nome.setText(tf_nome.getText().substring(0, 12));
                    lb_nomeIconeHumor.setText(tf_nome.getText().toUpperCase()+" "+tf_sobrenome.getText().toUpperCase());
                    MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_EXCESSO_CARACT_12, "aviso");

                }
                    else{
                        lb_contaNome.setText("("+String.valueOf(tf_nome.getText().length())+")");
                    }
        }
    }//GEN-LAST:event_tf_nomeKeyReleased

    private void tf_sobrenomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_sobrenomeKeyReleased
        if(!SolicitarDados.s_SolicitarDados.verificaCaracteresInvalidosCadastro(tf_sobrenome.getText())){
            tf_sobrenome.setText(tf_sobrenome.getText().substring(0, (tf_sobrenome.getText().length() -1)));
            String l_msg = Avisos.MSG_USE_SEG_NOME_SEM_ESP;
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(l_msg, "aviso");
            tf_sobrenome.requestFocus();
        }else{

            lb_nomeIconeHumor.setText(tf_nome.getText()+" "+tf_sobrenome.getText().toUpperCase());
            tf_sobrenome.setText(tf_sobrenome.getText().toUpperCase());

                if(tf_sobrenome.getText().length() > 15){
                    lb_contaSobrenome.setText("(15)");
                    tf_sobrenome.setText(tf_sobrenome.getText().substring(0, 15));
                    lb_nomeIconeHumor.setText(tf_nome.getText()+" "+tf_sobrenome.getText().toUpperCase());
                    MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_EXCESSO_CARACT_15, "aviso");
                }
                    else{
                        lb_contaSobrenome.setText("("+String.valueOf(tf_sobrenome.getText().length())+")");
                    }
        }
    }//GEN-LAST:event_tf_sobrenomeKeyReleased

    private void tf_moniersnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_moniersnKeyReleased
        if(!SolicitarDados.s_SolicitarDados.verificaCaracteresInvalidosCadastro(tf_moniersn.getText())){
            tf_moniersn.setText(tf_moniersn.getText().substring(0, (tf_moniersn.getText().length() -1)));
            String l_msg = Avisos.MSG_APELIDO_SEM_SIMB_OU_ESP;
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(l_msg, "aviso");
            tf_moniersn.requestFocus();
        }else{

            lb_IconeHumorApelido.setText(tf_moniersn.getText().toLowerCase());
            tf_moniersn.setText(tf_moniersn.getText().toLowerCase());
                if(tf_moniersn.getText().length() > 15){
                    lb_contaApelido.setText("(15)");
                    MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_EXCESSO_CARACT_15, "aviso");
                    tf_moniersn.setText(tf_moniersn.getText().substring(0, 15));
                }
                    else{
                        lb_contaApelido.setText("("+String.valueOf(tf_moniersn.getText().length())+")");
                    }
        }
    }//GEN-LAST:event_tf_moniersnKeyReleased

    private void bt_confirmaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_confirmaCadastroActionPerformed

        if(cb_concorda.isSelected()){

            new Thread(new auxiliar.threads.CadastroUsuario()).start(); 

            //mostra tela carregando
            Aguardando.s_telaAguardando.setVisible(true); 
        }else{
        
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_CONCORDE_TERMOS_E_POLITICA, "aviso");
        } 
        
        
    }//GEN-LAST:event_bt_confirmaCadastroActionPerformed

    private void cb_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_diaActionPerformed
        String l_data = null;
        Date l_dataTipoDate = null;
        if(!cb_dia.getSelectedItem().toString().isEmpty()){
            l_data = cb_dia.getSelectedItem().toString()+"-"+cb_mes.getSelectedItem().toString()+"-"+cb_ano.getSelectedItem().toString();
            lb_dataNascimento.setText(l_data);
            cb_mes.setEnabled(true);

                if(cb_mes.isEnabled() && cb_ano.isEnabled()){
                    l_data = cb_dia.getSelectedItem().toString()+"-"+cb_mes.getSelectedItem().toString()+"-"+cb_ano.getSelectedItem().toString();
                    l_dataTipoDate = Data.pegaDataTipoDateDDMMAAAA(l_data, Data.DD_MM_AAAA);
                    lb_dataNiver.setText(Data.pegaDataPorExtenso(l_dataTipoDate, Data.DIA_MES));
                }
            

        }
            else{
                lb_dataNascimento.setText("");
                cb_mes.setSelectedItem("");
                cb_ano.setSelectedItem("");
                cb_mes.setEnabled(false);
                cb_ano.setEnabled(false);
            }
    }//GEN-LAST:event_cb_diaActionPerformed

    private void cb_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_mesActionPerformed
        Date l_dataTipoDate = null;
        String l_data = null;
        if(!cb_mes.getSelectedItem().toString().isEmpty()){
            l_data = cb_dia.getSelectedItem().toString()+"-"+cb_mes.getSelectedItem().toString()+"-"+cb_ano.getSelectedItem().toString();
            lb_dataNascimento.setText(l_data);
            cb_ano.setEnabled(true);

                if(cb_ano.isEnabled() && !cb_ano.getSelectedItem().toString().equals("")){
                    l_data = cb_dia.getSelectedItem().toString()+"-"+cb_mes.getSelectedItem().toString()+"-"+cb_ano.getSelectedItem().toString();
                    l_dataTipoDate = Data.pegaDataTipoDateDDMMAAAA(l_data, Data.DD_MM_AAAA);
                    lb_dataNiver.setText(Data.pegaDataPorExtenso(l_dataTipoDate, Data.DIA_MES));
                }

        }
            else{
                cb_ano.setEnabled(false);
                cb_ano.setSelectedItem("");
                lb_dataNascimento.setText(cb_dia.getSelectedItem().toString()); 
            }
    }//GEN-LAST:event_cb_mesActionPerformed

    private void cb_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_anoActionPerformed
        String l_data = null;
        Date l_dataTipoDate = null;

        if(!cb_ano.getSelectedItem().toString().isEmpty()){

            l_data = cb_dia.getSelectedItem().toString()+"-"+cb_mes.getSelectedItem().toString()+"-"+cb_ano.getSelectedItem().toString();
            lb_dataNascimento.setText(l_data);
            l_dataTipoDate = Data.pegaDataTipoDateDDMMAAAA(l_data, Data.DD_MM_AAAA);
            lb_dataNiver.setText(Data.pegaDataPorExtenso(l_dataTipoDate, Data.DIA_MES));
        }
            else{
                l_data = cb_dia.getSelectedItem().toString()+"-"+cb_mes.getSelectedItem().toString();
                lb_dataNascimento.setText(l_data);
                lb_dataNiver.setText("");
            }
    }//GEN-LAST:event_cb_anoActionPerformed

    private void tf_resposta_secretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_resposta_secretaActionPerformed
        if(cb_concorda.isSelected()){

            new Thread(new auxiliar.threads.CadastroUsuario()).start(); 

            //mostra tela carregando
            Aguardando.s_telaAguardando.setVisible(true); 
        }else{
        
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_CONCORDE_TERMOS_E_POLITICA, "aviso");
            cb_concorda.requestFocus();
        }
    }//GEN-LAST:event_tf_resposta_secretaActionPerformed

    private void tf_nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_nomeFocusLost
        tf_nome.setText(tf_nome.getText().toUpperCase());
    }//GEN-LAST:event_tf_nomeFocusLost

    private void tf_sobrenomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_sobrenomeFocusLost
        tf_sobrenome.setText(tf_sobrenome.getText().toUpperCase());
    }//GEN-LAST:event_tf_sobrenomeFocusLost

    private void tf_moniersnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_moniersnFocusLost
        tf_moniersn.setText(tf_moniersn.getText().toLowerCase()); 
    }//GEN-LAST:event_tf_moniersnFocusLost

    private void tf_resposta_secretaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_resposta_secretaKeyReleased
            tf_resposta_secreta.setText(tf_resposta_secreta.getText().toLowerCase());
    }//GEN-LAST:event_tf_resposta_secretaKeyReleased

    private void cb_concordaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_concordaActionPerformed
        if(cb_concorda.isSelected())
            bt_confirmaCadastro.setEnabled(true);
        else
            bt_confirmaCadastro.setEnabled(false);
 
    }//GEN-LAST:event_cb_concordaActionPerformed

    private void lb_politicaPrivMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_politicaPrivMouseReleased
        MostrarDados.s_MostrarDados.abreDoc("politica-priv"); 
    }//GEN-LAST:event_lb_politicaPrivMouseReleased

    private void lb_termosUsoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_termosUsoMouseReleased
        MostrarDados.s_MostrarDados.abreDoc("termos-uso"); 
    }//GEN-LAST:event_lb_termosUsoMouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroUsuario dialog = new CadastroUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bt_confirmaCadastro;
    public static javax.swing.JButton bt_confirmar;
    public javax.swing.JComboBox cb_ano;
    private javax.swing.JCheckBox cb_concorda;
    public javax.swing.JComboBox cb_dia;
    public javax.swing.JComboBox cb_humor;
    public javax.swing.JComboBox cb_mes;
    public static javax.swing.JComboBox cb_pergunta_secreta;
    private javax.swing.ButtonGroup gb_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public static javax.swing.JPanel jp_infoSeguranca;
    private javax.swing.JLabel lb_IconeHumorApelido;
    private javax.swing.JLabel lb_contaApelido;
    private javax.swing.JLabel lb_contaNome;
    private javax.swing.JLabel lb_contaSobrenome;
    private javax.swing.JLabel lb_dataCadatro;
    private javax.swing.JLabel lb_dataNascimento;
    private javax.swing.JLabel lb_dataNiver;
    private javax.swing.JLabel lb_iconeFeminino;
    private javax.swing.JLabel lb_iconeMasculino;
    private javax.swing.JLabel lb_iconeSexo;
    private javax.swing.JLabel lb_nomeIconeHumor;
    private javax.swing.JLabel lb_politicaPriv;
    private javax.swing.JLabel lb_sexo;
    private javax.swing.JLabel lb_termosUso;
    public static javax.swing.JPasswordField pf_conf_senha;
    public static javax.swing.JPasswordField pf_senha;
    public javax.swing.JRadioButton rb_feminino;
    public javax.swing.JRadioButton rb_masculino;
    public static javax.swing.JTextField tf_moniersn;
    public javax.swing.JTextField tf_nome;
    public static javax.swing.JTextField tf_resposta_secreta;
    public javax.swing.JTextField tf_sobrenome;
    // End of variables declaration//GEN-END:variables


}//fim da classe
