/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Comentario.java
 *
 * Created on 09/02/2011, 00:10:31
 */

package formularios;

import auxiliar.GravarDados;
import auxiliar.MostrarDados;
import auxiliar.AtualizarDados;
import auxiliar.Avisos;
import auxiliar.LogUsuario;
import javax.swing.JTable;

/**
 *
 * @author Ayrton Monier
 */
public class Comentario extends javax.swing.JDialog {

    public static Comentario s_telaComentario;

    public static boolean s_mostrandoComentarios;

    //GUARDA O TIPO DE COMENTÁRIO EM QUESTÃO (recado/ocorrencia)
    public String c_tipoComentario;
    public JTable c_tabela;
    public int c_codConteudo;
    public String c_apelidoEmissor;

    /** Creates new form Comentario */
    public Comentario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        try{
            initComponents();
        }catch(Exception e){
            System.err.println("erro: "+e);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jp_fundoRecado = new javax.swing.JPanel();
        lb_dataPostagem = new javax.swing.JLabel();
        lb_conteudo = new javax.swing.JLabel();
        lb_emissorConteudo = new javax.swing.JLabel();
        lb_destinatarioConteudo = new javax.swing.JLabel();
        lb_indicador = new javax.swing.JLabel();
        lb_ultimaAtu = new javax.swing.JLabel();
        lb_qtdComentsEncontrada = new javax.swing.JLabel();
        lb_pesquisarComents = new javax.swing.JLabel();
        tf_conteudoComentsPesquisado = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        sp_comentario = new javax.swing.JScrollPane();
        jt_listaComentarios = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        tf_comentario = new javax.swing.JTextField();
        lb_qtdComentarios1 = new javax.swing.JLabel();
        lb_descricaoConteudo = new javax.swing.JLabel();
        lb_interrogacao = new javax.swing.JLabel();
        bt_comentar = new javax.swing.JButton();
        js_separador4 = new javax.swing.JSeparator();
        lb_descricaoPrivConteudo = new javax.swing.JLabel();
        cb_comentarioAnonimo = new javax.swing.JCheckBox();
        bt_removerComent = new javax.swing.JButton();
        lb_qtdComentarios = new javax.swing.JLabel();
        bt_inicio = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jp_fundoRecado.setBackground(new java.awt.Color(0, 0, 204));
        jp_fundoRecado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_dataPostagem.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lb_dataPostagem.setForeground(new java.awt.Color(255, 255, 255));
        lb_dataPostagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/hora-add.png"))); // NOI18N
        lb_dataPostagem.setText("Quando:");

        lb_conteudo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lb_conteudo.setForeground(new java.awt.Color(255, 255, 255));
        lb_conteudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ocorrencia-add.png"))); // NOI18N
        lb_conteudo.setText("CONTEUDO");

        lb_emissorConteudo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lb_emissorConteudo.setForeground(new java.awt.Color(255, 255, 255));
        lb_emissorConteudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/humor/novato.png"))); // NOI18N
        lb_emissorConteudo.setText("Emissor");
        lb_emissorConteudo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Emissor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        lb_destinatarioConteudo.setFont(new java.awt.Font("Trebuchet MS", 1, 13)); // NOI18N
        lb_destinatarioConteudo.setForeground(new java.awt.Color(255, 255, 255));
        lb_destinatarioConteudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/humor/novato.png"))); // NOI18N
        lb_destinatarioConteudo.setText("Destinatário");
        lb_destinatarioConteudo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Destinatário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        lb_indicador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_indicador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/40/legal.png"))); // NOI18N
        lb_indicador.setToolTipText("Achou legal??? Clique aqui!");
        lb_indicador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_indicador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_indicadorMouseReleased(evt);
            }
        });

        lb_ultimaAtu.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lb_ultimaAtu.setForeground(new java.awt.Color(255, 255, 255));
        lb_ultimaAtu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_ultimaAtu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/hora-atualizar.png"))); // NOI18N
        lb_ultimaAtu.setText("Ultima atu.:");

        javax.swing.GroupLayout jp_fundoRecadoLayout = new javax.swing.GroupLayout(jp_fundoRecado);
        jp_fundoRecado.setLayout(jp_fundoRecadoLayout);
        jp_fundoRecadoLayout.setHorizontalGroup(
            jp_fundoRecadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_fundoRecadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_fundoRecadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_fundoRecadoLayout.createSequentialGroup()
                        .addComponent(lb_emissorConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_destinatarioConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_fundoRecadoLayout.createSequentialGroup()
                        .addComponent(lb_indicador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_fundoRecadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_fundoRecadoLayout.createSequentialGroup()
                                .addComponent(lb_dataPostagem, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_ultimaAtu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lb_conteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jp_fundoRecadoLayout.setVerticalGroup(
            jp_fundoRecadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_fundoRecadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_fundoRecadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lb_indicador, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_fundoRecadoLayout.createSequentialGroup()
                        .addComponent(lb_conteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_fundoRecadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_dataPostagem)
                            .addComponent(lb_ultimaAtu))
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_fundoRecadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_emissorConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_destinatarioConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lb_qtdComentsEncontrada.setText("(999) Encontradas");

        lb_pesquisarComents.setText("Pesquisar comentario:");

        tf_conteudoComentsPesquisado.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tf_conteudoComentsPesquisado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_conteudoComentsPesquisadoKeyReleased(evt);
            }
        });

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/mostra_mais_conteudo.png"))); // NOI18N
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/atualizar-lista.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        sp_comentario.setFocusTraversalPolicyProvider(true);

        jt_listaComentarios.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jt_listaComentarios.setForeground(new java.awt.Color(255, 0, 0));
        jt_listaComentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "*", "De", "Comentário", "Quando"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt_listaComentarios.setGridColor(new java.awt.Color(0, 0, 204));
        jt_listaComentarios.setRowHeight(35);
        jt_listaComentarios.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jt_listaComentarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jt_listaComentarios.setShowHorizontalLines(false);
        jt_listaComentarios.setShowVerticalLines(false);
        jt_listaComentarios.getTableHeader().setReorderingAllowed(false);
        jt_listaComentarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jt_listaComentariosMouseReleased(evt);
            }
        });
        sp_comentario.setViewportView(jt_listaComentarios);

        jPanel3.setBackground(new java.awt.Color(239, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tf_comentario.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        tf_comentario.setForeground(new java.awt.Color(255, 0, 0));
        tf_comentario.setCaretColor(new java.awt.Color(255, 0, 0));
        tf_comentario.setFocusTraversalPolicyProvider(true);
        tf_comentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_comentarioActionPerformed(evt);
            }
        });

        lb_qtdComentarios1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lb_qtdComentarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/comentario.png"))); // NOI18N

        lb_descricaoConteudo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lb_descricaoConteudo.setForeground(new java.awt.Color(255, 255, 255));
        lb_descricaoConteudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/comentario-add.png"))); // NOI18N
        lb_descricaoConteudo.setText("Comente esta ocorrência logo abaixo ¬");
        lb_descricaoConteudo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lb_descricaoConteudo.setFocusTraversalPolicyProvider(true);

        lb_interrogacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_interrogacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/40/duvida.png"))); // NOI18N
        lb_interrogacao.setToolTipText("Não entendeu??? Clique aqui!");
        lb_interrogacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_interrogacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_interrogacaoMouseReleased(evt);
            }
        });

        bt_comentar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bt_comentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/comentario-add.png"))); // NOI18N
        bt_comentar.setText("Comentar");
        bt_comentar.setToolTipText("Comentar este conteúdo");
        bt_comentar.setFocusTraversalPolicyProvider(true);
        bt_comentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_comentarActionPerformed(evt);
            }
        });

        lb_descricaoPrivConteudo.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lb_descricaoPrivConteudo.setForeground(new java.awt.Color(255, 255, 255));
        lb_descricaoPrivConteudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/informacao.png"))); // NOI18N
        lb_descricaoPrivConteudo.setText("Todos(geral) ou Todos(amigos) estão vizualizando");
        lb_descricaoPrivConteudo.setFocusTraversalPolicyProvider(true);

        cb_comentarioAnonimo.setBackground(new java.awt.Color(239, 0, 0));
        cb_comentarioAnonimo.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        cb_comentarioAnonimo.setForeground(new java.awt.Color(255, 255, 255));
        cb_comentarioAnonimo.setText("Anônimo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lb_interrogacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_descricaoConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lb_qtdComentarios1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_comentario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_comentarioAnonimo)
                                .addGap(6, 6, 6)
                                .addComponent(bt_comentar)))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(js_separador4)
                            .addComponent(lb_descricaoPrivConteudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lb_descricaoConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_qtdComentarios1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_comentario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bt_comentar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_comentarioAnonimo))))
                    .addComponent(lb_interrogacao, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(js_separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_descricaoPrivConteudo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_removerComent.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bt_removerComent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/comentario-remocao.png"))); // NOI18N
        bt_removerComent.setText("Remover");
        bt_removerComent.setToolTipText("Remover comentário selecionado");
        bt_removerComent.setEnabled(false);
        bt_removerComent.setFocusTraversalPolicyProvider(true);
        bt_removerComent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_removerComentActionPerformed(evt);
            }
        });

        lb_qtdComentarios.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        lb_qtdComentarios.setForeground(new java.awt.Color(0, 0, 255));
        lb_qtdComentarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/comentario-ocorrencia.png"))); // NOI18N
        lb_qtdComentarios.setText("(999) Comentário(s)");
        lb_qtdComentarios.setToolTipText("");
        lb_qtdComentarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_qtdComentarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_qtdComentariosMouseReleased(evt);
            }
        });

        bt_inicio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bt_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/inicio.png"))); // NOI18N
        bt_inicio.setText("Início");
        bt_inicio.setToolTipText("Voltar ao início...");
        bt_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inicioActionPerformed(evt);
            }
        });

        bt_voltar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bt_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ocorrencia-novo.png"))); // NOI18N
        bt_voltar.setText("Voltar");
        bt_voltar.setToolTipText("Volte para tela anterior...");
        bt_voltar.setFocusTraversalPolicyProvider(true);
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_qtdComentsEncontrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_pesquisarComents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_conteudoComentsPesquisado, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(sp_comentario)
                    .addComponent(jp_fundoRecado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_qtdComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_removerComent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_fundoRecado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_qtdComentarios)
                    .addComponent(bt_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_removerComent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sp_comentario, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_qtdComentsEncontrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_pesquisarComents, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_conteudoComentsPesquisado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Moniersn.s_telaMsn.setVisible(true);
        Comentario.s_telaComentario = null;
        System.out.println("Tela de comentario fechada e valor null");
    }//GEN-LAST:event_formWindowClosing

    private void bt_comentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_comentarActionPerformed
        String l_texto   = tf_comentario.getText().toString().toUpperCase();
     
        GravarDados.s_GravarDados.gravarComentario(c_codConteudo, c_tipoComentario, l_texto, cb_comentarioAnonimo.isSelected(), c_tabela, c_apelidoEmissor);
    }//GEN-LAST:event_bt_comentarActionPerformed

    private void tf_comentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_comentarioActionPerformed
        String l_texto = tf_comentario.getText().toString().toUpperCase();

        GravarDados.s_GravarDados.gravarComentario(c_codConteudo, c_tipoComentario, l_texto, cb_comentarioAnonimo.isSelected(), c_tabela, c_apelidoEmissor);
    }//GEN-LAST:event_tf_comentarioActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        dispose();
        Comentario.s_telaComentario = null;
        Moniersn.s_telaMsn.setVisible(true);
        System.out.println("Tela de comentario fechada e valor null"); 
    }//GEN-LAST:event_bt_voltarActionPerformed

    private void bt_removerComentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_removerComentActionPerformed
       AtualizarDados.s_AtualizarDados.removerConteudo(jt_listaComentarios);
    }//GEN-LAST:event_bt_removerComentActionPerformed

    private void jt_listaComentariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_listaComentariosMouseReleased
        MostrarDados.s_MostrarDados.habilitaBotoesConteudo(jt_listaComentarios); 
    }//GEN-LAST:event_jt_listaComentariosMouseReleased

    private void bt_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inicioActionPerformed
        dispose();
        Comentario.s_telaComentario = null;
        Moniersn.s_telaMsn.setVisible(true);
        System.out.println("Tela de comentario fechada e valor null");     
        Moniersn.jtp_painelTabuladoUsuario.setSelectedComponent(Moniersn.jp_inicioUsuario);
}//GEN-LAST:event_bt_inicioActionPerformed

private void tf_conteudoComentsPesquisadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_conteudoComentsPesquisadoKeyReleased
        //inabilitação de botao de comentário de ocorrencia
        bt_removerComent.setEnabled(false);       
    
        //preencher lista de ocorrências do amigo
        MostrarDados.s_MostrarDados.preencherListaComentarios(c_codConteudo, c_tipoComentario);
}//GEN-LAST:event_tf_conteudoComentsPesquisadoKeyReleased

private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        LogUsuario.s_qtdComentAMostrar += 4;
            
        //inabilitação de botao de comentário de ocorrencia
        bt_removerComent.setEnabled(false);       
    
        //preencher lista de ocorrências do amigo
        MostrarDados.s_MostrarDados.preencherListaComentarios(c_codConteudo, c_tipoComentario);
        
        sp_comentario.getVerticalScrollBar().setValue(jt_listaComentarios.getSize().height); 
}//GEN-LAST:event_jButton19ActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        LogUsuario.s_qtdComentAMostrar = 4;
        tf_conteudoComentsPesquisado.setText("");
    
        //inabilitação de botao de comentário de ocorrencia
        bt_removerComent.setEnabled(false);       
    
        //preencher lista de ocorrências do amigo
        MostrarDados.s_MostrarDados.preencherListaComentarios(c_codConteudo, c_tipoComentario);
}//GEN-LAST:event_jButton10ActionPerformed

private void lb_indicadorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_indicadorMouseReleased

        String l_texto   = Avisos.COMENTARIO_LEGAL;
     
        GravarDados.s_GravarDados.gravarComentario(c_codConteudo, c_tipoComentario, l_texto, false, c_tabela, c_apelidoEmissor);
}//GEN-LAST:event_lb_indicadorMouseReleased

private void lb_interrogacaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_interrogacaoMouseReleased
        
        String l_texto   = Avisos.COMENTARIO_N_ENTENDI;
     
        GravarDados.s_GravarDados.gravarComentario(c_codConteudo, c_tipoComentario, l_texto, false, c_tabela, c_apelidoEmissor);

}//GEN-LAST:event_lb_interrogacaoMouseReleased

private void lb_qtdComentariosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_qtdComentariosMouseReleased
        if(s_mostrandoComentarios){
            MostrarDados.s_MostrarDados.mostraComentarios(false);
        }
        else{
            MostrarDados.s_MostrarDados.mostraComentarios(true);
        }
}//GEN-LAST:event_lb_qtdComentariosMouseReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Comentario dialog = new Comentario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_comentar;
    private javax.swing.JButton bt_inicio;
    public javax.swing.JButton bt_removerComent;
    public static javax.swing.JButton bt_voltar;
    public static javax.swing.JCheckBox cb_comentarioAnonimo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jp_fundoRecado;
    private javax.swing.JSeparator js_separador4;
    public static javax.swing.JTable jt_listaComentarios;
    public static javax.swing.JLabel lb_conteudo;
    public static javax.swing.JLabel lb_dataPostagem;
    public static javax.swing.JLabel lb_descricaoConteudo;
    public static javax.swing.JLabel lb_descricaoPrivConteudo;
    public static javax.swing.JLabel lb_destinatarioConteudo;
    public static javax.swing.JLabel lb_emissorConteudo;
    public static javax.swing.JLabel lb_indicador;
    public static javax.swing.JLabel lb_interrogacao;
    public static javax.swing.JLabel lb_pesquisarComents;
    public static javax.swing.JLabel lb_qtdComentarios;
    public javax.swing.JLabel lb_qtdComentarios1;
    public static javax.swing.JLabel lb_qtdComentsEncontrada;
    public static javax.swing.JLabel lb_ultimaAtu;
    private javax.swing.JScrollPane sp_comentario;
    public javax.swing.JTextField tf_comentario;
    public static javax.swing.JTextField tf_conteudoComentsPesquisado;
    // End of variables declaration//GEN-END:variables

}
