/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CompartilhaArquivo.java
 *
 * Created on 22/11/2011, 13:13:16
 */

package formularios;
import auxiliar.Avisos;
import auxiliar.Icones;
import javax.swing.ImageIcon;
import auxiliar.MostrarDados;
import auxiliar.threads.PreparaCompartilhamentoArquivo;
import auxiliar.SolicitarDados;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
/**
 *
 * @author Ayrton Monier
 */
public class CompartilhaArquivo extends javax.swing.JFrame {

    public static CompartilhaArquivo s_telaCompArquivo;

    public String c_comQuemCompartilha = null;
    public String c_nomeExtensaoArquivoSelecionado = null;
    public String c_nomeArquivoSelecionado = null;
    public String  c_novoNome = null;
    public int c_codDestinatario;
    public int c_tempoMostraErro = 0;
    public byte[] c_bytesArquivo;

    /** Creates new form CompartilhaArquivo */
    public CompartilhaArquivo() {
        initComponents();

        
        this.setTitle(Avisos.TIT_JAN_COMP_ARQ); 
        tf_arquivo.setSelectionColor(Color.red);
        tf_arquivo.setSelectionStart(0);
        lb_preparando.setVisible(false);
        MostrarDados.s_MostrarDados.carregalistaAmigosEnvArquivo();

        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc_selecionadorArquivo = new javax.swing.JFileChooser();
        bg_destinatarios = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lb_logo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rb_amigosGeral = new javax.swing.JRadioButton();
        rb_unicoAmigo = new javax.swing.JRadioButton();
        rb_todosGeral = new javax.swing.JRadioButton();
        cb_listaAmigos = new javax.swing.JComboBox();
        lb_iconePessoa = new javax.swing.JLabel();
        lb_iconeConfirmarDestinatario = new javax.swing.JLabel();
        lb_preparando = new javax.swing.JLabel();
        bt_compartilhar = new javax.swing.JButton();
        lb_arquivoTipo = new javax.swing.JLabel();
        tf_diretorio = new javax.swing.JTextField();
        tf_arquivo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_extensao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_tamanho = new javax.swing.JTextField();
        bt_cancelar = new javax.swing.JButton();
        bt_selecionarArquivo = new javax.swing.JButton();
        pb_barraPreparandoArquivo = new javax.swing.JProgressBar();
        bt_confirmarRenomear = new javax.swing.JButton();
        lb_iconeTipoArquivo = new javax.swing.JLabel();
        bt_editarCampo = new javax.swing.JButton();
        lb_nomeOriginal = new javax.swing.JLabel();
        lb_tamanhoMb = new javax.swing.JLabel();

        fc_selecionadorArquivo.setApproveButtonText("Selecionar");
        fc_selecionadorArquivo.setDialogTitle("");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(CompartilhaArquivo.class.getResource(Icones.ARQUIVO_ADD), "Facecard MS").getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/logo-disponibiliza-arquivo.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quem poderá baixar?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        rb_amigosGeral.setBackground(new java.awt.Color(255, 255, 255));
        bg_destinatarios.add(rb_amigosGeral);
        rb_amigosGeral.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        rb_amigosGeral.setForeground(new java.awt.Color(255, 0, 0));
        rb_amigosGeral.setText("Amigos(geral)");
        rb_amigosGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rb_amigosGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_amigosGeralActionPerformed(evt);
            }
        });

        rb_unicoAmigo.setBackground(new java.awt.Color(255, 255, 255));
        bg_destinatarios.add(rb_unicoAmigo);
        rb_unicoAmigo.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        rb_unicoAmigo.setForeground(new java.awt.Color(255, 0, 0));
        rb_unicoAmigo.setText("Uma pessoa");
        rb_unicoAmigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rb_unicoAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_unicoAmigoActionPerformed(evt);
            }
        });

        rb_todosGeral.setBackground(new java.awt.Color(255, 255, 255));
        bg_destinatarios.add(rb_todosGeral);
        rb_todosGeral.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        rb_todosGeral.setForeground(new java.awt.Color(255, 0, 0));
        rb_todosGeral.setText("Todos(geral)");
        rb_todosGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rb_todosGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_todosGeralActionPerformed(evt);
            }
        });

        cb_listaAmigos.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        cb_listaAmigos.setForeground(new java.awt.Color(255, 0, 0));

        lb_iconePessoa.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lb_iconePessoa.setForeground(new java.awt.Color(0, 0, 204));
        lb_iconePessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/amigo.png"))); // NOI18N

        lb_iconeConfirmarDestinatario.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lb_iconeConfirmarDestinatario.setForeground(new java.awt.Color(0, 0, 204));
        lb_iconeConfirmarDestinatario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_iconeConfirmarDestinatario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        lb_iconeConfirmarDestinatario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_iconeConfirmarDestinatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_iconeConfirmarDestinatarioMouseReleased(evt);
            }
        });

        lb_preparando.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lb_preparando.setForeground(new java.awt.Color(0, 0, 204));
        lb_preparando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/aguardando.gif"))); // NOI18N
        lb_preparando.setText("preparando...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lb_preparando, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lb_iconePessoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_listaAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_iconeConfirmarDestinatario))
                    .addComponent(rb_todosGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(rb_unicoAmigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(rb_amigosGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(rb_unicoAmigo)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_iconeConfirmarDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cb_listaAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_iconePessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_todosGeral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_amigosGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lb_preparando)
                .addContainerGap())
        );

        bt_compartilhar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bt_compartilhar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        bt_compartilhar.setText("Compartilhar o arquivo com...");
        bt_compartilhar.setToolTipText("Compartilhar arquivo");
        bt_compartilhar.setEnabled(false);
        bt_compartilhar.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        bt_compartilhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_compartilharActionPerformed(evt);
            }
        });

        lb_arquivoTipo.setFont(new java.awt.Font("Trebuchet MS", 3, 12)); // NOI18N
        lb_arquivoTipo.setForeground(new java.awt.Color(0, 0, 204));
        lb_arquivoTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/informacao.png"))); // NOI18N
        lb_arquivoTipo.setText("SELECIONE QUEM PODERÁ BAIXAR...");

        tf_diretorio.setEditable(false);
        tf_diretorio.setForeground(new java.awt.Color(255, 0, 0));

        tf_arquivo.setEditable(false);
        tf_arquivo.setForeground(new java.awt.Color(255, 0, 0));
        tf_arquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_arquivoActionPerformed(evt);
            }
        });
        tf_arquivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_arquivoKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Local:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Extensão:");

        tf_extensao.setEditable(false);
        tf_extensao.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Tamanho (bytes):");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/informacao.png"))); // NOI18N
        jLabel7.setText("O arquivo só ficará disponível se você estiver conectado");

        tf_tamanho.setEditable(false);
        tf_tamanho.setForeground(new java.awt.Color(255, 0, 0));

        bt_cancelar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/cancelar.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_selecionarArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/procurar.png"))); // NOI18N
        bt_selecionarArquivo.setToolTipText("Selecionar arquivo");
        bt_selecionarArquivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_selecionarArquivo.setEnabled(false);
        bt_selecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_selecionarArquivoActionPerformed(evt);
            }
        });

        pb_barraPreparandoArquivo.setBackground(new java.awt.Color(255, 255, 255));
        pb_barraPreparandoArquivo.setForeground(new java.awt.Color(0, 0, 204));
        pb_barraPreparandoArquivo.setToolTipText("");
        pb_barraPreparandoArquivo.setBorderPainted(false);

        bt_confirmarRenomear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        bt_confirmarRenomear.setToolTipText("Confirmar novo nome");
        bt_confirmarRenomear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_confirmarRenomear.setEnabled(false);
        bt_confirmarRenomear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_confirmarRenomearActionPerformed(evt);
            }
        });

        lb_iconeTipoArquivo.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lb_iconeTipoArquivo.setForeground(new java.awt.Color(0, 0, 204));
        lb_iconeTipoArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/arquivos.png"))); // NOI18N

        bt_editarCampo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/editar-campo.png"))); // NOI18N
        bt_editarCampo.setToolTipText("Liberar para renomear");
        bt_editarCampo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_editarCampo.setEnabled(false);
        bt_editarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarCampoActionPerformed(evt);
            }
        });

        lb_nomeOriginal.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        lb_nomeOriginal.setForeground(new java.awt.Color(255, 0, 0));
        lb_nomeOriginal.setText("*");

        lb_tamanhoMb.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        lb_tamanhoMb.setForeground(new java.awt.Color(0, 0, 204));
        lb_tamanhoMb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_tamanhoMb.setText("(0,0 MB)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_extensao)
                                    .addComponent(jLabel2))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_tamanho))
                                .addGap(104, 104, 104)
                                .addComponent(lb_tamanhoMb, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_diretorio)
                            .addComponent(lb_arquivoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_iconeTipoArquivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb_nomeOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(tf_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_editarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_confirmarRenomear, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5)
                                        .addComponent(bt_selecionarArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_compartilhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pb_barraPreparandoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lb_arquivoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lb_nomeOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb_iconeTipoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_arquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bt_confirmarRenomear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_editarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(bt_selecionarArquivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(8, 8, 8)
                        .addComponent(tf_diretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_extensao)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_tamanho)
                                .addComponent(lb_tamanhoMb, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_compartilhar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pb_barraPreparandoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_amigosGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_amigosGeralActionPerformed
        bt_selecionarArquivo.setEnabled(true);
        bt_compartilhar.setText(Avisos.TEXTO_COMPARTILHAR_ARQUIVO_COM+Avisos.TEXTO_AMIGOS_GERAL);
        cb_listaAmigos.setVisible(false);
        lb_iconePessoa.setVisible(false);
        lb_iconeConfirmarDestinatario.setVisible(false);
        lb_arquivoTipo.setText(Avisos.TEXTO_SELECIONE_O_ARQUIVO);

        c_comQuemCompartilha = "amigos";
        c_codDestinatario = 0;

        if(!tf_arquivo.getText().isEmpty() && !tf_arquivo.isEditable()){
            bt_compartilhar.setEnabled(true);
            lb_arquivoTipo.setText(Avisos.TEXTO_ARQ_PRONTO_PARA_COMPART);
        }else if((!tf_arquivo.getText().isEmpty() || !lb_nomeOriginal.getText().equals("*")) && tf_arquivo.isEditable()){
            bt_compartilhar.setEnabled(false);
            lb_arquivoTipo.setText(Avisos.TEXTO_DE_UM_NOME_PESSOAL_AO_ARQ);
        }else{
            bt_compartilhar.setEnabled(false);
            lb_arquivoTipo.setText(Avisos.TEXTO_SELECIONE_O_ARQUIVO);
        }
    }//GEN-LAST:event_rb_amigosGeralActionPerformed

    private void rb_unicoAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_unicoAmigoActionPerformed
        bt_compartilhar.setEnabled(false);
        bt_selecionarArquivo.setEnabled(false);
        bt_compartilhar.setText(Avisos.TEXTO_COMPARTILHAR_ARQUIVO_COM+"...");
        lb_arquivoTipo.setText(Avisos.TEXTO_SELECIONE_ALGUEM_ESPECIFICO);

        if(cb_listaAmigos.getItemCount() <= 0){

            lb_iconePessoa.setVisible(true);
            lb_iconePessoa.setText(Avisos.TEXTO_NINGUEM_ESP_AINDA);
            cb_listaAmigos.setVisible(false);
            lb_iconeConfirmarDestinatario.setVisible(false);

        } else{
            lb_iconePessoa.setVisible(true);
            cb_listaAmigos.setVisible(true);
            lb_iconeConfirmarDestinatario.setVisible(true);

            cb_listaAmigos.setEnabled(true);
            lb_iconeConfirmarDestinatario.setEnabled(true);
        }
    }//GEN-LAST:event_rb_unicoAmigoActionPerformed

    private void rb_todosGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_todosGeralActionPerformed
        
        bt_selecionarArquivo.setEnabled(true);
        bt_compartilhar.setText(Avisos.TEXTO_COMPARTILHAR_ARQUIVO_COM+Avisos.TEXTO_TODOS_GERAL);
        cb_listaAmigos.setVisible(false);
        lb_iconePessoa.setVisible(false);
        lb_iconeConfirmarDestinatario.setVisible(false);

        c_comQuemCompartilha = "todos";
        c_codDestinatario = 0;

        if(!tf_arquivo.getText().isEmpty() && !tf_arquivo.isEditable()){
            bt_compartilhar.setEnabled(true);
            lb_arquivoTipo.setText(Avisos.TEXTO_ARQ_PRONTO_PARA_COMPART);
        }else if((!tf_arquivo.getText().isEmpty() || !lb_nomeOriginal.getText().equals("*")) && tf_arquivo.isEditable()){
            bt_compartilhar.setEnabled(false);
            lb_arquivoTipo.setText(Avisos.TEXTO_DE_UM_NOME_PESSOAL_AO_ARQ);
        }else{
            bt_compartilhar.setEnabled(false);
            lb_arquivoTipo.setText(Avisos.TEXTO_SELECIONE_O_ARQUIVO);
        }
}//GEN-LAST:event_rb_todosGeralActionPerformed

    private void lb_iconeConfirmarDestinatarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_iconeConfirmarDestinatarioMouseReleased
        if(!tf_arquivo.getText().isEmpty() && !tf_arquivo.isEditable()){
            bt_compartilhar.setEnabled(true);
            lb_arquivoTipo.setText(Avisos.TEXTO_ARQ_PRONTO_PARA_COMPART);
        }else if((!tf_arquivo.getText().isEmpty() || !lb_nomeOriginal.getText().equals("*")) && tf_arquivo.isEditable()){
            lb_arquivoTipo.setText(Avisos.TEXTO_DE_UM_NOME_PESSOAL_AO_ARQ);
        }else
            lb_arquivoTipo.setText(Avisos.TEXTO_SELECIONE_O_ARQUIVO);
        
        c_comQuemCompartilha = cb_listaAmigos.getSelectedItem().toString();
        bt_selecionarArquivo.setEnabled(true);
        cb_listaAmigos.setEnabled(false);
        lb_iconeConfirmarDestinatario.setEnabled(false);
        bt_compartilhar.setText(Avisos.TEXTO_COMPARTILHAR_ARQUIVO_COM+cb_listaAmigos.getSelectedItem());
        

        //pega cod do amigo selecionado na lista
        c_codDestinatario = SolicitarDados.pegaCodigoPeloApelido(cb_listaAmigos.getSelectedItem().toString());
    }//GEN-LAST:event_lb_iconeConfirmarDestinatarioMouseReleased

    private void bt_compartilharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_compartilharActionPerformed

        bt_compartilhar.setEnabled(false);
        bt_cancelar.setEnabled(false);
        bt_selecionarArquivo.setEnabled(false);
        lb_preparando.setVisible(true);
        s_telaCompArquivo.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        String l_comQuem = c_comQuemCompartilha;
        int l_codDest = c_codDestinatario;
        String l_nomeArq = c_nomeExtensaoArquivoSelecionado;
        String l_novoNome = c_novoNome;
        String l_extensaoArq = tf_extensao.getText();
        String l_diretorioArq = tf_diretorio.getText()+"\\"+l_nomeArq;
        long l_tamanhoArq = Long.parseLong(tf_tamanho.getText());

        //preparando compartilhamento de arquivo
        System.out.println("Iniciando Thread de preparação de compartilhamento de arquivo...");
        PreparaCompartilhamentoArquivo pComp = new PreparaCompartilhamentoArquivo(l_comQuem, l_codDest, l_nomeArq, l_novoNome, l_extensaoArq, l_diretorioArq, l_tamanhoArq);

        new Thread(pComp).start();
}//GEN-LAST:event_bt_compartilharActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        dispose();
        s_telaCompArquivo = null;
        Moniersn.s_telaMsn.setVisible(true);
}//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_selecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_selecionarArquivoActionPerformed

        String l_diretorio;
        String l_extensao = null;
        String l_tipoArquivo = null;
        String l_iconeArquivo = null;
        String l_tamanho = null;
        
        boolean l_selecaoOk = false;
        double l_tamanhoMb = 0;

        File l_arquivoSelecionado = null;

        fc_selecionadorArquivo = new JFileChooser();
            
            if(!tf_diretorio.getText().isEmpty()){
                fc_selecionadorArquivo.setCurrentDirectory(new File(tf_diretorio.getText())); 
            }

        do{

           int res = fc_selecionadorArquivo.showOpenDialog(null);

           fc_selecionadorArquivo.setDialogTitle(Avisos.TIT_JAN_ESC_ARQ);

                if(res == JFileChooser.APPROVE_OPTION){

                    //somente até 50 mb
                    if(fc_selecionadorArquivo.getSelectedFile().length() <= 50000000){

                        l_selecaoOk = true;

                        //PEGA DADOS DO ARQUIVO
                        l_arquivoSelecionado = fc_selecionadorArquivo.getSelectedFile();

                        //NOME COM EXTENSAO
                        c_nomeExtensaoArquivoSelecionado = l_arquivoSelecionado.getName();

                        //DIRETÓRIO
                        l_diretorio = l_arquivoSelecionado.getParent();

                        //TAMANHO
                        l_tamanho = String.valueOf(l_arquivoSelecionado.length());

                        l_tamanhoMb = (Integer.parseInt(l_tamanho) / 1024) / 1024;

                        //EXTENSAO
                        l_extensao = SolicitarDados.s_SolicitarDados.pegaExtensaoOuNomeArquivo(c_nomeExtensaoArquivoSelecionado, "extensao");

        //                c_bytesArquivo = new byte[(int) l_arquivoSelecionado.length()];
        //
        //                c_bytesArquivo = SolicitarDados.s_SolicitarDados.pegaBytesArquivo(l_arquivoSelecionado);

                        //SETA DADOS NA TELA

                        //SETA NOME
                        tf_arquivo.setText("");
                        tf_arquivo.setEditable(true);
                        tf_arquivo.requestFocus();


                        //SETA ICONE EXTENSAO ARQUIVO
                        l_iconeArquivo = SolicitarDados.s_SolicitarDados.pegaIconeOuTipoExtensao(l_extensao, "icone");
                        lb_iconeTipoArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource(l_iconeArquivo))); // NOI18N

                        //SETA TIPO ARQUIVO
                        l_tipoArquivo = SolicitarDados.s_SolicitarDados.pegaIconeOuTipoExtensao(l_extensao, "tipo");
                        lb_arquivoTipo.setText(Avisos.TEXTO_DE_UM_NOME_PESSOAL_AO_ARQ);

                        String l_nomeArquivo50carac = SolicitarDados.s_SolicitarDados.trataNomeArquivoPara50caracteres(c_nomeExtensaoArquivoSelecionado);

                        //SETA O NOME ORIGINAL DO ARQUIVO
                        lb_nomeOriginal.setText("("+l_tipoArquivo+") "+l_nomeArquivo50carac);

                        //SETA DIRETÓRIO (LOCAL DO ARQUIVO)
                        tf_diretorio.setText(l_diretorio);

                        //EXTENSÃO
                        tf_extensao.setText(l_extensao);

                        //TAMANHO BYTES
                        tf_tamanho.setText(l_tamanho);

                        //TAMANHO MB
                        lb_tamanhoMb.setText(l_tamanhoMb+" MB");

                        //CONFIRMAR NOME DO ARQUIVO
                        bt_compartilhar.setEnabled(false);
                        bt_confirmarRenomear.setEnabled(true);
                        bt_editarCampo.setEnabled(false);

                    }else{
                        MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ARQ_MUITO_GRANDE, "erro");
                        l_selecaoOk = false;
                    }


                }else if(res == JFileChooser.CANCEL_OPTION){
                    if(tf_diretorio.getText().isEmpty())
                        MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ARQ_NAO_SELEC, "aviso");
                    
                    l_selecaoOk = true;
                }

        }while (!l_selecaoOk);
    }//GEN-LAST:event_bt_selecionarArquivoActionPerformed

    private void bt_confirmarRenomearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_confirmarRenomearActionPerformed

        if(tf_arquivo.getText().isEmpty()){

            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ARQ_INFORME_NOME, "aviso");
            tf_arquivo.requestFocus();

        }else{


            boolean l_nomeOk = false;
            String l_novoNome = tf_arquivo.getText();
            String l_extensao = tf_extensao.getText();
            String l_nomeCompletoArq = l_novoNome+l_extensao;


                if(SolicitarDados.s_SolicitarDados.nomeArquivoJaFoiUsado(l_nomeCompletoArq)){

                    l_nomeOk = SolicitarDados.s_SolicitarDados.verificaCaracteresInvalidosNomeArquivo(l_novoNome);

                        if(l_nomeOk){

                            //CONFIRMAR NOME DO ARQUIVO
                            c_novoNome = l_novoNome+l_extensao;
                            tf_arquivo.setEditable(false);
                            bt_confirmarRenomear.setEnabled(false);
                            bt_editarCampo.setEnabled(true);
                            
                                
                                if(rb_unicoAmigo.isSelected() || rb_amigosGeral.isSelected() || rb_todosGeral.isSelected()){
                                    
                                    if(rb_unicoAmigo.isSelected() && cb_listaAmigos.isEnabled()){
                                        lb_arquivoTipo.setText(Avisos.TEXTO_SELECIONE_ALGUEM_ESPECIFICO);
                                        bt_compartilhar.setEnabled(false);
                                    }else{
                                        lb_arquivoTipo.setText(Avisos.TEXTO_ARQ_PRONTO_PARA_COMPART);
                                        bt_compartilhar.setEnabled(true);
                                    }
                                
                                //caso destinatario nao selecionado
                                }else{
                                    lb_arquivoTipo.setText(Avisos.TEXTO_SELECIONE_QUEM_BAIXA_ARQ);
                                    bt_compartilhar.setEnabled(false);
                                }
                                

                        }else{

                            System.out.println("Contem caracteres invalidos.");
                            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ARQ_CARACT_INV, "aviso");

                        }

                }

        }
}//GEN-LAST:event_bt_confirmarRenomearActionPerformed

    
    
    
    private void bt_editarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarCampoActionPerformed

        bt_editarCampo.setEnabled(false);
        tf_arquivo.setEditable(true);
        tf_arquivo.requestFocus();
        bt_confirmarRenomear.setEnabled(true);
        bt_compartilhar.setEnabled(false);
        lb_arquivoTipo.setText(Avisos.TEXTO_DE_UM_NOME_PESSOAL_AO_ARQ);
    }//GEN-LAST:event_bt_editarCampoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        s_telaCompArquivo = null;
        Moniersn.s_telaMsn.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void tf_arquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_arquivoActionPerformed
        if(tf_arquivo.getText().isEmpty()){

            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ARQ_INFORME_NOME, "aviso");
            tf_arquivo.requestFocus();

        }else{


            boolean l_nomeOk = false;
            String l_novoNome = tf_arquivo.getText();
            String l_extensao = tf_extensao.getText();
            String l_nomeCompletoArq = l_novoNome+l_extensao;


                if(SolicitarDados.s_SolicitarDados.nomeArquivoJaFoiUsado(l_nomeCompletoArq)){

                    l_nomeOk = SolicitarDados.s_SolicitarDados.verificaCaracteresInvalidosNomeArquivo(l_novoNome);

                        if(l_nomeOk){

                            //CONFIRMAR NOME DO ARQUIVO
                            c_novoNome = l_novoNome+l_extensao;
                            bt_compartilhar.setEnabled(true);
                            tf_arquivo.setEditable(false);
                            bt_confirmarRenomear.setEnabled(false);
                            bt_editarCampo.setEnabled(true);


                        }else{

                            System.out.println("Contem caracteres invalidos.");
                            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ARQ_CARACT_INV, "aviso");

                        }

                }

        }
    }//GEN-LAST:event_tf_arquivoActionPerformed

private void tf_arquivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_arquivoKeyReleased
        if(!SolicitarDados.s_SolicitarDados.verificaCaracteresInvalidosNomeArquivo(tf_arquivo.getText())){
            tf_arquivo.setText(tf_arquivo.getText().substring(0, (tf_arquivo.getText().length() -1)));
            String l_msg = Avisos.MSG_ARQ_CARACT_INV;
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(l_msg, "aviso");
            tf_arquivo.requestFocus();
        }else{

            tf_arquivo.setText(tf_arquivo.getText().toUpperCase());
                if(tf_arquivo.getText().length() > 50){
                    MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_EXCESSO_CARACT_50, "aviso");
                    tf_arquivo.setText(tf_arquivo.getText().substring(0, 50));
                }
        }
}//GEN-LAST:event_tf_arquivoKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompartilhaArquivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_destinatarios;
    public javax.swing.JButton bt_cancelar;
    public javax.swing.JButton bt_compartilhar;
    public javax.swing.JButton bt_confirmarRenomear;
    public javax.swing.JButton bt_editarCampo;
    public javax.swing.JButton bt_selecionarArquivo;
    public static javax.swing.JComboBox cb_listaAmigos;
    private javax.swing.JFileChooser fc_selecionadorArquivo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lb_arquivoTipo;
    public javax.swing.JLabel lb_iconeConfirmarDestinatario;
    public javax.swing.JLabel lb_iconePessoa;
    public javax.swing.JLabel lb_iconeTipoArquivo;
    public javax.swing.JLabel lb_logo;
    public javax.swing.JLabel lb_nomeOriginal;
    public javax.swing.JLabel lb_preparando;
    public javax.swing.JLabel lb_tamanhoMb;
    public static javax.swing.JProgressBar pb_barraPreparandoArquivo;
    public javax.swing.JRadioButton rb_amigosGeral;
    public javax.swing.JRadioButton rb_todosGeral;
    public javax.swing.JRadioButton rb_unicoAmigo;
    public javax.swing.JTextField tf_arquivo;
    public javax.swing.JTextField tf_diretorio;
    public javax.swing.JTextField tf_extensao;
    public javax.swing.JTextField tf_tamanho;
    // End of variables declaration//GEN-END:variables

}
