/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DecisaoDeSolicitacaoDeAmizade.java
 *
 * Created on 25/04/2010, 12:16:07
 */

package formularios;
import auxiliar.Avisos;
import auxiliar.GravarDados;
import auxiliar.LogUsuario;

/**
 *
 * @author ayrton monier
 */
public class DecisaoDeSolicitacaoDeAmizade extends javax.swing.JDialog {

    int c_contador = 0;
    public static DecisaoDeSolicitacaoDeAmizade s_telaSolicitacaoAmizade;

    //variável de classe do tipo String
    public String c_decisao;

    //cod amigo
    public int c_codAmigo;

    /** Creates new form DecisaoDeSolicitacaoDeAmizade */
    public DecisaoDeSolicitacaoDeAmizade(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setTitle(Avisos.TIT_JAN_SOLIC_AMIZADE); 

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_aceitar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_aceitar = new javax.swing.JRadioButton();
        lb_nome = new javax.swing.JLabel();
        lb_solicitacaoAmizade = new javax.swing.JLabel();
        lb_tempoQueAdd = new javax.swing.JLabel();
        bt_ok = new javax.swing.JButton();
        rb_naoAceitar = new javax.swing.JRadioButton();
        rb_lembrar = new javax.swing.JRadioButton();
        bt_cancelar = new javax.swing.JButton();
        lb_comprimento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("");
        setAlwaysOnTop(true);
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        rb_aceitar.setBackground(new java.awt.Color(255, 255, 255));
        bg_aceitar.add(rb_aceitar);
        rb_aceitar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        rb_aceitar.setForeground(new java.awt.Color(255, 0, 0));
        rb_aceitar.setText("Sim, aceitar solicitação de amizade.");
        rb_aceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_aceitarActionPerformed(evt);
            }
        });

        lb_nome.setFont(new java.awt.Font("Comic Sans MS", 3, 17)); // NOI18N
        lb_nome.setForeground(new java.awt.Color(255, 0, 0));
        lb_nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/humor/novato.png"))); // NOI18N
        lb_nome.setText("nome");
        lb_nome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quem", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        lb_solicitacaoAmizade.setFont(new java.awt.Font("Trebuchet MS", 1, 24));
        lb_solicitacaoAmizade.setForeground(new java.awt.Color(0, 0, 204));
        lb_solicitacaoAmizade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/logo-solicitacao-amizade-rec.png"))); // NOI18N

        lb_tempoQueAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lb_tempoQueAdd.setForeground(new java.awt.Color(0, 0, 255));
        lb_tempoQueAdd.setText("ele(a) me add a tanto tempo");

        bt_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        bt_ok.setText("Ok");
        bt_ok.setEnabled(false);
        bt_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_okActionPerformed(evt);
            }
        });

        rb_naoAceitar.setBackground(new java.awt.Color(255, 255, 255));
        bg_aceitar.add(rb_naoAceitar);
        rb_naoAceitar.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        rb_naoAceitar.setForeground(new java.awt.Color(255, 0, 0));
        rb_naoAceitar.setText("Não, ignorar solicitação de amizade.");
        rb_naoAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_naoAceitarActionPerformed(evt);
            }
        });

        rb_lembrar.setBackground(new java.awt.Color(255, 255, 255));
        bg_aceitar.add(rb_lembrar);
        rb_lembrar.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        rb_lembrar.setForeground(new java.awt.Color(255, 0, 0));
        rb_lembrar.setText("Depois eu vejo.");
        rb_lembrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_lembrarActionPerformed(evt);
            }
        });

        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/cancelar.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        lb_comprimento.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        lb_comprimento.setForeground(new java.awt.Color(255, 0, 0));
        lb_comprimento.setText("Comprimentação");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_ok, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cancelar)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lb_comprimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_solicitacaoAmizade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 373, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rb_aceitar, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rb_lembrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_naoAceitar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_tempoQueAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_solicitacaoAmizade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_comprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_tempoQueAdd)
                .addGap(7, 7, 7)
                .addComponent(rb_aceitar, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_naoAceitar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_lembrar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_aceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_aceitarActionPerformed
        c_decisao = "aceitar";
        bt_ok.setEnabled(true);
    }//GEN-LAST:event_rb_aceitarActionPerformed

    private void rb_naoAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_naoAceitarActionPerformed
        c_decisao = "ignorar";
        bt_ok.setEnabled(true);
    }//GEN-LAST:event_rb_naoAceitarActionPerformed

    private void bt_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_okActionPerformed
        s_telaSolicitacaoAmizade.dispose();
        LogUsuario.s_mostrandoSolicitacaoAmizade = false;

            //CASO O USUÁRIO DESEJA ACEITAR UMA SOLICITAÇÃO
            if(c_decisao.equals("aceitar")){

                   //remover o amigo em questao
                   GravarDados.s_GravarDados.aceitarSolicitacaoAmizade(c_codAmigo);
            }

            //CASO O USUÁRIO DESEJA IGNORAR UMA SOLICITAÇÃO
            if(c_decisao.equals("ignorar")){

                   //remover o amigo em questao
                   GravarDados.s_GravarDados.ignorarSolicitacaoAmizade(c_codAmigo);
            }
         
         s_telaSolicitacaoAmizade = null;
    }//GEN-LAST:event_bt_okActionPerformed

    private void rb_lembrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_lembrarActionPerformed
        c_decisao = "depois";
        bt_ok.setEnabled(true);
    }//GEN-LAST:event_rb_lembrarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
         s_telaSolicitacaoAmizade.dispose();
         LogUsuario.s_mostrandoSolicitacaoAmizade = false;
         s_telaSolicitacaoAmizade = null;
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
             s_telaSolicitacaoAmizade.dispose();
             LogUsuario.s_mostrandoSolicitacaoAmizade = false;
             s_telaSolicitacaoAmizade = null;
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DecisaoDeSolicitacaoDeAmizade.s_telaSolicitacaoAmizade = new DecisaoDeSolicitacaoDeAmizade(new javax.swing.JFrame(), true);
                DecisaoDeSolicitacaoDeAmizade.s_telaSolicitacaoAmizade.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                DecisaoDeSolicitacaoDeAmizade.s_telaSolicitacaoAmizade.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_aceitar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_ok;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lb_comprimento;
    public javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_solicitacaoAmizade;
    public javax.swing.JLabel lb_tempoQueAdd;
    private javax.swing.JRadioButton rb_aceitar;
    private javax.swing.JRadioButton rb_lembrar;
    private javax.swing.JRadioButton rb_naoAceitar;
    // End of variables declaration//GEN-END:variables

   
}
