/*
 * To change this template, choose Tools | Templates |
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 07/03/2010, 18:59:29
 */

package formularios;

import auxiliar.*;
import auxiliar.threads.ConectaFacecard;
import auxiliar.threads.LogoCarregando;
import auxiliar.threads.SobreFacecard;
import javax.swing.*;

/**
 *
 * @author ayrton monier!
 */
public class Login extends javax.swing.JFrame{

    public static Login s_telaLogin;
    
    public static boolean l_cadIniciado = false;


    
    /** Creates new form Login */
    public Login() {
        
        initComponents();
        
        this.setTitle(Avisos.TIT_JAN_LOGIN); 

        Dados.s_conexaoBanco.conecta();
        
        //preenche lista de apelidos da lista
        MostrarDados.s_MostrarDados.carregaItensComboBox(cb_apelido, "usuario", "moniersn");
        
        
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pf_senha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        lb_oqueEh = new javax.swing.JLabel();
        lb_cadastrar = new javax.swing.JLabel();
        lb_esquiciSenha = new javax.swing.JLabel();
        bt_conectar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_fechar = new javax.swing.JButton();
        cb_apelido = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(new ImageIcon(Login.class.getResource("/imagens/icones/16/icone-notificacao.png"), Avisos.FACECARD_FULL).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Selecione seu apelido:");

        pf_senha.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        pf_senha.setForeground(new java.awt.Color(255, 0, 0));
        pf_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_senhaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setToolTipText("");

        lb_oqueEh.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lb_oqueEh.setForeground(new java.awt.Color(0, 0, 153));
        lb_oqueEh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_oqueEh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/op-login-sobre-facecard-b.png"))); // NOI18N
        lb_oqueEh.setToolTipText("Saiba um pouco mais sobre o Facecard!");
        lb_oqueEh.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lb_oqueEh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_oqueEh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_oqueEhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_oqueEhMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_oqueEhMouseReleased(evt);
            }
        });

        lb_cadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lb_cadastrar.setForeground(new java.awt.Color(0, 0, 153));
        lb_cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/op-login-criar-facecard-b.png"))); // NOI18N
        lb_cadastrar.setToolTipText("Crie seu Facecard rápido e fácil!");
        lb_cadastrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lb_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_cadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_cadastrarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_cadastrarMouseReleased(evt);
            }
        });

        lb_esquiciSenha.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        lb_esquiciSenha.setForeground(new java.awt.Color(0, 0, 153));
        lb_esquiciSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_esquiciSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/op-login-esqueci-senha-b.png"))); // NOI18N
        lb_esquiciSenha.setToolTipText("Resgate sua senha informando a resposta secreta!");
        lb_esquiciSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lb_esquiciSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_esquiciSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_esquiciSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_esquiciSenhaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lb_esquiciSenhaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_esquiciSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_oqueEh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_esquiciSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_cadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_oqueEh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_conectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/conectado.png"))); // NOI18N
        bt_conectar.setToolTipText("Conectar");
        bt_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_conectarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Senha:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo/logo-facecard.gif"))); // NOI18N
        jLabel3.setToolTipText("Visite o nosso site e saiba mais: www.facecardbymonier.com");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        bt_fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/cancelar.png"))); // NOI18N
        bt_fechar.setToolTipText("Fechar");
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });

        cb_apelido.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cb_apelido.setToolTipText("Se ja criou o seu, selecione nesta lista e depois informe a sua senha...");
        cb_apelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_apelidoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("facecardbymonier.com");
        jLabel7.setToolTipText("Saiba mais no nosso site!");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/amigo-r.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Copyright © 2012.");
        jLabel5.setToolTipText("Todos os direitos reservados à Ayrton Monier");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cb_apelido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pf_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_conectar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pf_senha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cb_apelido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void lb_cadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_cadastrarMouseEntered
        lb_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/op-login-criar-facecard-r.png"))); // NOI18N
    }//GEN-LAST:event_lb_cadastrarMouseEntered

    private void lb_esquiciSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_esquiciSenhaMouseEntered
        lb_esquiciSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/op-login-esqueci-senha-r.png")));
    }//GEN-LAST:event_lb_esquiciSenhaMouseEntered

    private void bt_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_conectarActionPerformed
        //método que vai buscar informações referente ao usuário
        
        if(cb_apelido.getSelectedItem().toString().equals("*")){
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_SELECIONE_APELIDO, "aviso");
            cb_apelido.requestFocus();
        }
        
        else if(pf_senha.getText().isEmpty()){
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_INFORME_SENHA_LOGIN, "aviso");
            pf_senha.requestFocus();
        }
        
        else{
            
            String l_apelido = cb_apelido.getSelectedItem().toString();
            String l_senha = pf_senha.getText();
            
            new Thread(new ConectaFacecard(l_apelido, l_senha)).start(); 
            
            //mostra tela carregando
            Aguardando.s_telaAguardando.setVisible(true); 
            
        }
        
    }//GEN-LAST:event_bt_conectarActionPerformed

    private void pf_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_senhaActionPerformed
        //método que vai buscar informações referente ao usuário
        if(cb_apelido.getSelectedItem().toString().isEmpty()){
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_SELECIONE_APELIDO, "aviso");
            cb_apelido.requestFocus();
        }
        else if(pf_senha.getText().isEmpty()){
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_INFORME_SENHA_LOGIN, "aviso");
            pf_senha.requestFocus();
        }
        else{
            
            String l_apelido = cb_apelido.getSelectedItem().toString();
            String l_senha = pf_senha.getText();
            
            
            new Thread(new ConectaFacecard(l_apelido, l_senha)).start(); 
            
            //mostra tela carregando
            Aguardando.s_telaAguardando.setVisible(true); 
        }
    }//GEN-LAST:event_pf_senhaActionPerformed

    private void lb_esquiciSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_esquiciSenhaMouseExited
        lb_esquiciSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/op-login-esqueci-senha-b.png")));
    }//GEN-LAST:event_lb_esquiciSenhaMouseExited

    private void lb_cadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_cadastrarMouseExited
        lb_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/op-login-criar-facecard-b.png"))); // NOI18N
    }//GEN-LAST:event_lb_cadastrarMouseExited

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
        Dados.s_conexaoBanco.desconecta();
        System.exit(0); 
    }//GEN-LAST:event_bt_fecharActionPerformed

    private void cb_apelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_apelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_apelidoActionPerformed

    private void lb_oqueEhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_oqueEhMouseExited
        lb_oqueEh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/op-login-sobre-facecard-b.png")));
    }//GEN-LAST:event_lb_oqueEhMouseExited

    private void lb_oqueEhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_oqueEhMouseEntered
        lb_oqueEh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/op-login-sobre-facecard-r.png")));
    }//GEN-LAST:event_lb_oqueEhMouseEntered

    private void lb_oqueEhMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_oqueEhMouseReleased
        //logo carregando...
        new Thread(new SobreFacecard()).start();
        Aguardando.s_telaAguardando.setVisible(true); 
        
        
        
    }//GEN-LAST:event_lb_oqueEhMouseReleased

    private void lb_cadastrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_cadastrarMouseReleased
        MostrarDados.s_MostrarDados.mostraTelaCadastro();
    }//GEN-LAST:event_lb_cadastrarMouseReleased

    private void lb_esquiciSenhaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_esquiciSenhaMouseReleased
        RecuperaSenha recupera = new RecuperaSenha(new javax.swing.JFrame(), true);
        recupera.setVisible(true);
    }//GEN-LAST:event_lb_esquiciSenhaMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_conectar;
    private javax.swing.JButton bt_fechar;
    public static javax.swing.JComboBox cb_apelido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_cadastrar;
    private javax.swing.JLabel lb_esquiciSenha;
    private javax.swing.JLabel lb_oqueEh;
    public static javax.swing.JPasswordField pf_senha;
    // End of variables declaration//GEN-END:variables

}//fim classe

