/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MensagemAtualizacao.java
 *
 * Created on 27/07/2011, 10:23:33
 */

package formularios;

import auxiliar.Avisos;
import auxiliar.Icones;
import java.awt.Color;

/**
 *
 * @author Ayrton Monier
 */
public class MensagemDialogo extends javax.swing.JDialog {

    int c_contador = 0;

    /** Creates new form MensagemAtualizacao */
    public MensagemDialogo(java.awt.Frame parent, boolean modal, String l_texto, String l_tipo) {
        super(parent, modal);
        initComponents();

        this.setTitle(Avisos.TIT_JAN_MENS_DIAL); 
        
        
        if(l_tipo.equals("erro")){

            jp_fundo.setBackground(Color.RED);
            lb_iconeTextoAviso.setForeground(Color.WHITE);
            lb_iconeTextoAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icones.ERRO_32)));

        }

        else if(l_tipo.equals("aviso")){

            jp_fundo.setBackground(Color.ORANGE);
            lb_iconeTextoAviso.setForeground(Color.BLACK);
            lb_iconeTextoAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icones.AVISO_32)));

        }

        else if(l_tipo.equals("atu")){

            jp_fundo.setBackground(Color.BLUE);
            lb_iconeTextoAviso.setForeground(Color.WHITE);
            lb_iconeTextoAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource(Icones.OK_32)));

        }


        lb_iconeTextoAviso.setText(l_texto);

        threadAviso.setDelay(1000);
        threadAviso.start();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        threadAviso = new org.netbeans.examples.lib.timerbean.Timer();
        jp_fundo = new javax.swing.JPanel();
        lb_iconeTextoAviso = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        threadAviso.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                threadAvisoOnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("");
        setAlwaysOnTop(true);
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jp_fundo.setBackground(new java.awt.Color(255, 0, 0));

        lb_iconeTextoAviso.setFont(new java.awt.Font("Trebuchet MS", 1, 14));
        lb_iconeTextoAviso.setForeground(new java.awt.Color(255, 255, 255));
        lb_iconeTextoAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/32/ok.png"))); // NOI18N
        lb_iconeTextoAviso.setText("texto");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jp_fundoLayout = new javax.swing.GroupLayout(jp_fundo);
        jp_fundo.setLayout(jp_fundoLayout);
        jp_fundoLayout.setHorizontalGroup(
            jp_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_fundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_iconeTextoAviso, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jp_fundoLayout.setVerticalGroup(
            jp_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_fundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_iconeTextoAviso)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_fundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void threadAvisoOnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threadAvisoOnTime
        c_contador++;

        if(c_contador == 3){
            this.dispose();
            threadAviso.stop();
        }
    }//GEN-LAST:event_threadAvisoOnTime

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            this.dispose();
            threadAviso.stop();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            this.dispose();
            threadAviso.stop();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
            this.dispose();
            threadAviso.stop();
    }//GEN-LAST:event_jButton1KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jp_fundo;
    public static javax.swing.JLabel lb_iconeTextoAviso;
    private org.netbeans.examples.lib.timerbean.Timer threadAviso;
    // End of variables declaration//GEN-END:variables

}
