/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PaletaEscolhaCor.java
 *
 * Created on 13/05/2010, 12:48:33
 */

package formularios;

import auxiliar.*;

/**
 *
 * @author ayrton monier
 */
public class PaletaEscolhaCor extends javax.swing.JDialog {

    public static PaletaEscolhaCor s_telaPaletaEscolhaCor;


    //variáveis de classe que irão guardar as o valor de c_r de c_g e c_b
    public int c_r, c_g, c_b;

    //variável de classe que vao guardar a cor propeiamente dita
    public String c_cor;

    //vai guarda o nome do campo no banc para fazer o UPDATE
    public String c_nomeCampoNoBanco = "";


 
    /** Creates new form PaletaEscolhaCor */
    public PaletaEscolhaCor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setTitle(Avisos.TIT_JAN_PAL_COR); 
        
        //seleciona a table de configurações de cores
        Dados.s_conexaoBanco.executeSELECT("select * from configuracoes_cores");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_logoTopo = new javax.swing.JLabel();
        bt_cancelar = new javax.swing.JButton();
        bt_visualizar = new javax.swing.JButton();
        bt_aceitaCor = new javax.swing.JButton();
        jp_painelTeste = new javax.swing.JPanel();
        lb_objeto = new javax.swing.JLabel();
        seletor_cores = new javax.swing.JColorChooser();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb_logoTopo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/logo-escolha-cores.png"))); // NOI18N

        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/cancelar.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_visualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/visualizar.png"))); // NOI18N
        bt_visualizar.setText("Visualizar");
        bt_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_visualizarActionPerformed(evt);
            }
        });

        bt_aceitaCor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        bt_aceitaCor.setText("Aceito");
        bt_aceitaCor.setEnabled(false);
        bt_aceitaCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_aceitaCorActionPerformed(evt);
            }
        });

        jp_painelTeste.setBorder(javax.swing.BorderFactory.createTitledBorder("Como vai ficar..."));

        lb_objeto.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        lb_objeto.setText("OBJETO");

        javax.swing.GroupLayout jp_painelTesteLayout = new javax.swing.GroupLayout(jp_painelTeste);
        jp_painelTeste.setLayout(jp_painelTesteLayout);
        jp_painelTesteLayout.setHorizontalGroup(
            jp_painelTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_painelTesteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_objeto, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_painelTesteLayout.setVerticalGroup(
            jp_painelTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_painelTesteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_objeto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        seletor_cores.setBackground(new java.awt.Color(255, 255, 255));
        seletor_cores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seletor_coresMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                seletor_coresMousePressed(evt);
            }
        });
        seletor_cores.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                seletor_coresComponentHidden(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_aceitaCor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_visualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cancelar))
                    .addComponent(seletor_cores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_painelTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_logoTopo, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_logoTopo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seletor_cores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_aceitaCor, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_painelTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void seletor_coresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seletor_coresMouseClicked
        bt_aceitaCor.setEnabled(false);
        //habilita botao de acitar
        bt_aceitaCor.setEnabled(true);

        //pega o valor red da cor selecionada
        c_r = seletor_cores.getColor().getRed();
        //pega o valor green da cor selecionada
        c_g = seletor_cores.getColor().getGreen();
        //pega o valor blue da cor selecionada
        c_b = seletor_cores.getColor().getBlue();

        //guarda o valr rgb na variável cor;
        c_cor = c_r+", "+c_g+", "+c_b;

            //caso o painel de fundo somente a cor do painel de teste mudará
            if(c_nomeCampoNoBanco.equals("cor_painel") || c_nomeCampoNoBanco.equals("cor_lista_recado") || c_nomeCampoNoBanco.equals("cor_lista_amigos"))
                jp_painelTeste.setBackground(new java.awt.Color(c_r, c_g, c_b));
            //caso seja algum label somente o label mudará de c_cor
            else
                lb_objeto.setForeground(new java.awt.Color(c_r, c_g, c_b));
}//GEN-LAST:event_seletor_coresMouseClicked

    private void bt_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_visualizarActionPerformed
        //habilita botao de acitar
        bt_aceitaCor.setEnabled(true);

        //pega o valor red da cor selecionada
        c_r = seletor_cores.getColor().getRed();
        //pega o valor green da cor selecionada
        c_g = seletor_cores.getColor().getGreen();
        //pega o valor blue da cor selecionada
        c_b = seletor_cores.getColor().getBlue();

        //guarda o valr rgb na variável cor;
        c_cor = c_r+", "+c_g+", "+c_b;

            //caso o painel de fundo somente a cor do painel de teste mudará
            if(c_nomeCampoNoBanco.equals("cor_painel") || c_nomeCampoNoBanco.equals("cor_lista_recado") || c_nomeCampoNoBanco.equals("cor_lista_amigos"))
                jp_painelTeste.setBackground(new java.awt.Color(c_r, c_g, c_b));
            //caso seja algum label somente o label mudará de c_cor
            else
                lb_objeto.setForeground(new java.awt.Color(c_r, c_g, c_b));
    }//GEN-LAST:event_bt_visualizarActionPerformed

    private void seletor_coresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seletor_coresMousePressed

    }//GEN-LAST:event_seletor_coresMousePressed

    private void bt_aceitaCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_aceitaCorActionPerformed
        try{

            //ATUALIZA COR NO BANCO
           String sqlUpdate = "UPDATE configuracoes_cores SET "+c_nomeCampoNoBanco+" = '"+c_cor+"' where cod_usuario = "+LogUsuario.s_cod;
           int mudou = auxiliar.Dados.s_conexaoBanco.c_statement.executeUpdate(sqlUpdate);

           //CASO ALTERADO...
           if(mudou == 1){

               //ATUALIZA CORES DO USUÁRIO
               Cores.s_Cores.atualizaCores(LogUsuario.s_cod, "usuario");

               //ATUALIZA CORES DA CONF DO USUÁRIO
               Cores.s_Cores.atualizaCores(LogUsuario.s_cod, "conf-usuario");


               dispose();
               s_telaPaletaEscolhaCor = null;
               System.out.println("tela de paleta escolha a cor fechada e null");
           }
        }
        catch(Exception e){
            System.err.println("Erro ao tentar atualizara cor no campo "+c_nomeCampoNoBanco+"!   \nErro:"+e);
        }
    }//GEN-LAST:event_bt_aceitaCorActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        dispose();
        s_telaPaletaEscolhaCor = null;
        System.out.println("tela de paleta escolha a cor fechada e null");

    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        s_telaPaletaEscolhaCor = null;
        System.out.println("tela de paleta escolha a cor fechada e null");

    }//GEN-LAST:event_formWindowClosing

    private void seletor_coresComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_seletor_coresComponentHidden
        System.out.println("deu certo...");
    }//GEN-LAST:event_seletor_coresComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_aceitaCor;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_visualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JPanel jp_painelTeste;
    private javax.swing.JLabel lb_logoTopo;
    public javax.swing.JLabel lb_objeto;
    private javax.swing.JColorChooser seletor_cores;
    // End of variables declaration//GEN-END:variables



}
