/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecuperaSenha.java
 *
 * Created on 19/04/2010, 12:43:41
 */

package formularios;
import auxiliar.*;
/**
 *
 * @author ayrton monier
 */
public class RecuperaSenha extends javax.swing.JDialog {

    public static RecuperaSenha s_telaRecuperaSenha;


    //variáveis de classe do tipo String
    private String c_respSecreta;
    private String c_senha;


    /** Creates new form RecuperaSenha */
    public RecuperaSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setTitle(Avisos.TIT_JAN_RECUP_SENHA); 
        lb_senha.setVisible(false);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cb_ano = new javax.swing.JComboBox();
        lb_senha = new javax.swing.JLabel();
        bt_verSenha = new javax.swing.JButton();
        tf_resposta_sec = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bt_ok1 = new javax.swing.JButton();
        cb_dia = new javax.swing.JComboBox();
        tf_nomeUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lb_perguntaSecreta = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bt_verPergunta = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cb_mes = new javax.swing.JComboBox();
        lb_senha1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Esqueci a senha - MonierSN");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cb_ano.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cb_ano.setForeground(new java.awt.Color(0, 0, 204));
        cb_ano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008" }));

        lb_senha.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lb_senha.setForeground(new java.awt.Color(255, 0, 0));
        lb_senha.setText("senha");

        bt_verSenha.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        bt_verSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        bt_verSenha.setText("Ver minha senha");
        bt_verSenha.setEnabled(false);
        bt_verSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verSenhaActionPerformed(evt);
            }
        });

        tf_resposta_sec.setEditable(false);
        tf_resposta_sec.setForeground(new java.awt.Color(255, 0, 0));
        tf_resposta_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_resposta_secActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("Resposta secreta:");

        bt_ok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        bt_ok1.setText("Terminei");
        bt_ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ok1ActionPerformed(evt);
            }
        });

        cb_dia.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cb_dia.setForeground(new java.awt.Color(0, 0, 204));
        cb_dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        tf_nomeUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tf_nomeUsuario.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/logo-esqueci-senha.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 204));
        jLabel16.setText("Pergunta secreta:");

        lb_perguntaSecreta.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lb_perguntaSecreta.setForeground(new java.awt.Color(255, 0, 0));
        lb_perguntaSecreta.setText("*");

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 204));
        jLabel14.setText("Apelido:");

        bt_verPergunta.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        bt_verPergunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/visualizar.png"))); // NOI18N
        bt_verPergunta.setText("Ver pergunta secreta");
        bt_verPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_verPerguntaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 204));
        jLabel13.setText("Data de nascimento:");

        cb_mes.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cb_mes.setForeground(new java.awt.Color(0, 0, 204));
        cb_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        lb_senha1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lb_senha1.setForeground(new java.awt.Color(0, 0, 204));
        lb_senha1.setText("Senha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf_nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_verPergunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lb_perguntaSecreta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_resposta_sec, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_senha1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_ok1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_verSenha))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cb_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cb_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_verPergunta)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_perguntaSecreta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_resposta_sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_verSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_senha1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_senha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bt_ok1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_verPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verPerguntaActionPerformed
        verPerguntaSecreta();
    }//GEN-LAST:event_bt_verPerguntaActionPerformed

    private void bt_verSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_verSenhaActionPerformed
       if(tf_resposta_sec.getText().toLowerCase().equals(c_respSecreta)){
           lb_senha.setText(c_senha);
           lb_senha.setVisible(true);
       }
       else{

           tf_resposta_sec.setText("");
           cb_dia.setSelectedItem("01");
           cb_mes.setSelectedItem("01");
           cb_ano.setSelectedItem("1960");
           lb_perguntaSecreta.setText("*");
           tf_resposta_sec.setEditable(false);
           bt_verSenha.setEnabled(true);
           lb_senha.setVisible(false);

           MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ERRO_RESP_SEC, "erro");
           
       }
    }//GEN-LAST:event_bt_verSenhaActionPerformed

    private void bt_ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ok1ActionPerformed
        dispose();
    }//GEN-LAST:event_bt_ok1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            s_telaRecuperaSenha = null;
            System.out.println("tela de recuperar senha fechada e valor null");
    }//GEN-LAST:event_formWindowClosing

    private void tf_resposta_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_resposta_secActionPerformed
       if(tf_resposta_sec.getText().toLowerCase().equals(c_respSecreta)){
           lb_senha.setText(c_senha);
           lb_senha.setVisible(true);
       }
       else{

           tf_resposta_sec.setText("");
           cb_dia.setSelectedItem("01");
           cb_mes.setSelectedItem("01");
           cb_ano.setSelectedItem("1960");
           lb_perguntaSecreta.setText("*");
           tf_resposta_sec.setEditable(false);
           bt_verSenha.setEnabled(true);
           lb_senha.setVisible(false);

           MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ERRO_RESP_SEC, "erro");
           
       }
    }//GEN-LAST:event_tf_resposta_secActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RecuperaSenha dialog = new RecuperaSenha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ok1;
    private javax.swing.JButton bt_verPergunta;
    private javax.swing.JButton bt_verSenha;
    private javax.swing.JComboBox cb_ano;
    private javax.swing.JComboBox cb_dia;
    private javax.swing.JComboBox cb_mes;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_perguntaSecreta;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JLabel lb_senha1;
    public javax.swing.JTextField tf_nomeUsuario;
    private javax.swing.JTextField tf_resposta_sec;
    // End of variables declaration//GEN-END:variables

    
    public void verPerguntaSecreta(){

        String l_dataTratada = null;
        String l_dataNascimento = null;
        String l_perguntaSecreta = null;

        Dados.s_conexaoBanco.executeSELECT("SELECT * FROM usuario WHERE moniersn = '"+tf_nomeUsuario.getText()+"'");
        try{    
            if(Dados.s_conexaoBanco.c_resultset.first()){

                l_dataNascimento = Dados.s_conexaoBanco.c_resultset.getString("data_nascimento");
                l_perguntaSecreta = Dados.s_conexaoBanco.c_resultset.getString("pergunta_secreta");
                c_senha = Dados.s_conexaoBanco.c_resultset.getString("senha");
                c_respSecreta = Dados.s_conexaoBanco.c_resultset.getString("resposta_secreta");
            }
            else
                MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ERRO_USUÁRIO, "erro");
        }
        catch(Exception e){

            System.err.println("Erro ao tentar buscar informações deste usuário.      \nErro: "+e);
            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ERRO_INESPERADO, "erro");
            
        }

        //manda valor do cb_dia, cb_mes e cb_ano para serem tratados na forma aaaa-mm-dd
        l_dataTratada = trataDataParaBanco(cb_dia.getSelectedItem().toString(), cb_mes.getSelectedItem().toString(), cb_ano.getSelectedItem().toString());

        if(l_dataNascimento.equals(l_dataTratada)){

            lb_perguntaSecreta.setText(l_perguntaSecreta+"?");

            //habilita o campo de resposta
            tf_resposta_sec.setEditable(true);
            bt_verSenha.setEnabled(true);
            tf_resposta_sec.requestFocus();

        }
        else{
            
            cb_dia.setSelectedItem("01");
            cb_mes.setSelectedItem("01");
            cb_ano.setSelectedItem("1960");
            cb_dia.requestFocus();

            MostrarDados.s_MostrarDados.mostraMensagemAtualizacao(Avisos.MSG_ERRO_DATA_NASC, "erro");
        }


    }

    //retorna a data tratada em aaa-mm-dd
    public String trataDataParaBanco(String dia, String mes, String ano){

       String l_data;

       l_data = ano+"-"+mes+"-"+dia;

       return l_data;

   }//fim regulariza data
}
