/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SolicitacaoDeAmizade.java
 *
 * Created on 23/08/2011, 17:58:44
 */

package formularios;
import auxiliar.Avisos;
import auxiliar.GravarDados;
import auxiliar.LogAmigo;
import javax.swing.Icon;
import auxiliar.LogUsuario;
/**
 *
 * @author Ayrton Monier
 */
public class SolicitacaoDeAmizade extends javax.swing.JDialog {

    int c_contador = 0;

    public static SolicitacaoDeAmizade s_telaConvite;



    /** Creates new form SolicitacaoDeAmizade */
    public SolicitacaoDeAmizade(java.awt.Frame parent, boolean modal, String l_nome, Icon l_icone, int l_codAmigo) {
        super(parent, modal);
        initComponents();

        this.setTitle(Avisos.TIT_JAN_SOLIC_AMIZADE); 
        
        lb_nome.setText(l_nome);
        lb_nome.setIcon(l_icone);
        LogUsuario.s_mostrandoTelaConvite = true;
        LogUsuario.s_codAmigoConvite = l_codAmigo;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_nome = new javax.swing.JLabel();
        bt_cancelar = new javax.swing.JButton();
        lb_solicitacaoAmizade = new javax.swing.JLabel();
        bt_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Convite - MonierSN");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb_nome.setFont(new java.awt.Font("Comic Sans MS", 3, 17)); // NOI18N
        lb_nome.setForeground(new java.awt.Color(255, 0, 0));
        lb_nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/humor/novato.png"))); // NOI18N
        lb_nome.setText("nome");
        lb_nome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Para", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        bt_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/cancelar.png"))); // NOI18N
        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        lb_solicitacaoAmizade.setFont(new java.awt.Font("Trebuchet MS", 1, 24));
        lb_solicitacaoAmizade.setForeground(new java.awt.Color(0, 0, 204));
        lb_solicitacaoAmizade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_solicitacaoAmizade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/grandes/logo-solicitacao-amizade-env.png"))); // NOI18N

        bt_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/16/ok.png"))); // NOI18N
        bt_ok.setText("Enviar solicitação");
        bt_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addComponent(lb_solicitacaoAmizade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_ok, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cancelar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_solicitacaoAmizade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_okActionPerformed
        //convidar um amigo
        GravarDados.s_GravarDados.convidarPessoa(LogAmigo.s_cod);
}//GEN-LAST:event_bt_okActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        s_telaConvite.dispose();
        LogUsuario.s_mostrandoTelaConvite = false;
        s_telaConvite = null;
}//GEN-LAST:event_bt_cancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        s_telaConvite.dispose();
        LogUsuario.s_mostrandoTelaConvite = false;
        s_telaConvite = null;
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_ok;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_solicitacaoAmizade;
    // End of variables declaration//GEN-END:variables

}
